### ISSUE TITLE
Add cm prototypes and sprites for ss14 content

### ISSUE THREAD

**Issue by QuietlyWhisper** [RMC-14/RMC-14#186]
- [x] #261
- [x] #262
- [x] #263
- [x] #589
- [x] #590
- [x] #672
- [x] #681
- [x] #680
- [x] #683
- [x] #685
- [x] #691 
- [x] #695 
- [x] #696
- [x] #744
- [x] #745
- [x] #747
- [x] #748
- [x] #749
- [x] #750
- [x] #751
- [x] #753
- [x] #755
- [x] #820
- [x] #821
- [x] #822
- [x] #823
- [x] #824
- [x] #825
- [x] #826
- [x] #827
- [x] #828
- [x] #830
- [x] #832
- [x] #833
- [x] #834
- [x] #835
- [x] #837
- [x] #838
- [x] #839
- [x] #854
- [x] #1016
- [x] #1159
- [x] #1160

**Comment by Tunguso4ka** [comment]
whisper/smug can you please add closets, lockers and crates to this list?

**Comment by QuietlyWhisper** [comment]
> whisper/smug can you please add closets, lockers and crates to this list?

I forgot crates

**Comment by Tunguso4ka** [comment]
Whisper, you probably should add "vender fills" too.

**Comment by QuietlyWhisper** [comment]
> Whisper, you probably should add "vender fills" too.

- #706

**Comment by QuietlyWhisper** [comment]
Added:
-  #852
-  #853
-  #854

**Comment by Tunguso4ka** [comment]
43/43 tasks. Done.
