### ISSUE TITLE
1 Drop Pouch

### ISSUE THREAD

**Issue by DrSmugleaf** [RMC-14/RMC-14#2258]

**Comment by diraven** [comment]
Duplicates https://github.com/RMC-14/RMC-14/issues/579.

**Comment by diraven** [comment]
Reopening since it's in some list I'm unable to edit and closing it leaves an impression it's done while it's not.

**Comment by Tunguso4ka** [comment]
> Duplicates #579.

it is not really a duplicate. Every item in ColMarTech issue have its own issue.
