### ISSUE TITLE
The M52CE2 needs weapon mounting for accuracy

### ISSUE THREAD

**Issue by gostt899** [RMC-14/RMC-14#2307]
## Description
The M52CE2 heavy pulse rifle no longer fires in automatic and is instead now single action when it should be automatic.

**Reproduction**
Grab the heavy pulse rifle. hold down M1 and it only fires one shot.

**Video**

https://github.com/CM-14/CM-14/assets/137981496/718a60ce-c747-4859-b0d9-305ee73d3b4c

**Comment by Dutch-VanDerLinde** [comment]
this is fixed
