### ISSUE TITLE
Flash is mapped into LV-624

### ISSUE THREAD

**Issue by DangerRevolution** [RMC-14/RMC-14#2349]
## Description

It shouldn't be

**Screenshots**

![image](https://github.com/CM-14/CM-14/assets/142105406/0a0705ee-c608-4a5b-9e9b-a2e2ee287f22)

**Comment by Tunguso4ka** [comment]
Just like in cm-ss13
![зображення](https://github.com/RMC-14/RMC-14/assets/71643624/998f9b99-5b93-432b-aabd-3194be7bdde7)
