### ISSUE TITLE
Marines have access to the main Medical bay (Alamyer issue)

### ISSUE THREAD

**Issue by DangerRevolution** [RMC-14/RMC-14#2356]
## Description

Title,

**Screenshots**

![image](https://github.com/CM-14/CM-14/assets/142105406/545190d9-04bb-4a2a-aac4-f3fc040790c6)
![image](https://github.com/CM-14/CM-14/assets/142105406/76f5b071-084a-4787-a986-cde4a79662a3)

**Comment by Tunguso4ka** [comment]
"actually, she's called Almayer https://cm-ss13.com/wiki/USS_Almayer not Alamayer"
🤓

**Comment by Tunguso4ka** [comment]
Fixed. Thank you Smug <3
