### ISSUE TITLE
Some autoinjectors have doafters; and some pouches may have wrong content.

### ISSUE THREAD

**Issue by DangerRevolution** [RMC-14/RMC-14#2357]
## Description

Going to update this after I play CM13 to cross check. I think contents are wrong and I can 100% confirm that the autoinjectors in the basic Medical pouches do not have doafters.
**Reproduction**

**Screenshots**

**Additional context**

**Comment by DrSmugleaf** [comment]
For the autoinjectors, its just the emergency and skillless tricordrazine that have no doafter for marines without medical training:

https://github.com/RMC-14/RMC-14/assets/10968691/8453004f-37f7-497f-a19e-e9231dc23bbe

Need to look through the pouches to see if any have incorrect fills though.

**Comment by DrSmugleaf** [comment]
Looking through I can't find any with wrong fills, but if there are any we will have them in separate issues
