### ISSUE TITLE
Backpack doafter

### ISSUE THREAD

**Issue by WarMechanic** [RMC-14/RMC-14#2387]
## Description

Backpacks require a doafter to open their inventories. However, you can use smart-equip from backpack to engage with your inventory without waiting for the interact time. This could use some consolidation.

**Comment by Tunguso4ka** [comment]
done?

**Comment by QuietlyWhisper** [comment]
Intended yeah

**Comment by Carolyn3114** [comment]
why is this intended

**Comment by Verification31** [comment]
backpacks have more space than satchels, so if they didnt have a doafter, then it would be a pure buff.
