### ISSUE TITLE
Windows are not breakable by reasonable means

### ISSUE THREAD

**Issue by Skarletto** [RMC-14/RMC-14#2504]
Video, left to right: a reinforced window (it drops 1 rod and takes 4 hits)), two normal windows (takes two hits each).

https://github.com/RMC-14/RMC-14/assets/122584947/a980f189-a284-4690-b27e-d9c1fd341cc4

Deconstructing a windowsil gives you 2 metal

**Comment by JoeHammad1844** [comment]
still a problem
