### ISSUE TITLE
Medical Pouches can't hold things they should be able to

### ISSUE THREAD

**Issue by SphiraI** [RMC-14/RMC-14#2514]
## Description
Will need a look over/verification from 13, but things like surgical cases, blood bags, and stasis bags can't be placed in medical pouches.

**Reproduction**
- Get medical pouch
- get various medical supplies like the listed above
- try and stuff them in

**Comment by Skarletto** [comment]
![image](https://github.com/CM-14/CM-14/assets/122584947/afab026e-7783-4080-b824-ad6b517d920f)

**Comment by tsp01** [comment]
I went to look at the CM code and compared it. First aid pouches can't hold roller beds, stasis bags, or surgical cases. The same is true for other medical pouches, excepting the medical kit pouch which can hold such things. I didn't find any particular discrepancies between our various medical pouches and CMs. Is there a specific item you are certain is supposed to be in these pouches?

**Comment by Skarletto** [comment]
> I went to look at the CM code and compared it. First aid pouches can't hold stasis bags, blood bags, or surgical cases. The same is true for other medical pouches, excepting the medical kit pouch which can hold such things. I didn't find any particular discrepancies between our various medical pouches and CMs. Is there a specific item you are certain is supposed to be in these pouches?

I don't believe the first aid pouches are missing anything, but the medkit pouch is definitely missing some items which I named above

**Comment by tsp01** [comment]
Well blood should be easy enough to fix, though I'm pretty sure there's a check preventing storage containers other than backpacks/satchels/duffle bags, from holding other storage containers, I'll take a look and see in an hour.
