### ISSUE TITLE
Machete from machete pouch is not unholstered by the unholster hotkeys

### ISSUE THREAD

**Issue by ShadowCommander** [RMC-14/RMC-14#2517]
## Description

Machete pouch doesn't get picked in by holster hotkeys.

**Reproduction**

- Unequip all unholster items. (gun, boot knife, etc.)
- Equip machete pouch.
- Try unholster hotkey.
- Machete is not pulled out.

**Comment by UnicornOnLSD** [comment]
yessir I need this
