### ISSUE TITLE
Double doors sometimes get confused on what side is open/closed

### ISSUE THREAD

**Issue by SphiraI** [RMC-14/RMC-14#2522]
## Description
Title. Occasionally, when walking through double doors, sides will get confused and have desynced hitboxes (one side blocking, other open, while the sprite displays both open)

**Reproduction**
Consistently, unknown. But it's possible to happen solo:
- be humanoid
- have double door
- keep opening and closing, while trying to block single sides
- eventually have an open sprite, but blocking hitbox

**Additional context**
When moving with 200 other players, through the same doors, this ends up happening a lot and creating really annoying to navigate doors.

**Comment by deltanedas** [comment]
it also blocks bullets not just players, which is extremely annoying

**Comment by deltanedas** [comment]
ok repro:
1. walk into a double door
2. wait for it to close
3. one side you are on is open other is closed
