### ISSUE TITLE
Ammo Boxes attach to Player when placed in ID/Dog Tag slot.

### ISSUE THREAD

**Issue by Willzile1** [RMC-14/RMC-14#2592]
## Description
If you attempt to place an ammo box in your ID slot on top of your dog tags, It attaches to your player. Still functions as normal, and allows you to carry much more ammo than intended. For some reason it caps at 3 boxes.

**Reproduction**
Grab any ammo or flare box into your hand, click the dog tag/ID card slot. You now have lots and lots of ammo to spam.

**Screenshots**
![image](https://github.com/RMC-14/RMC-14/assets/69917862/f105caf2-f2db-43ad-a72a-015c009a83ad)

**Additional context**
This may work for other inventory slots, I have yet to test them all.

**Comment by Vermidia** [comment]
Fixed by #3165
