### ISSUE TITLE
Medical staff start hungry

### ISSUE THREAD

**Issue by ShadowCommander** [RMC-14/RMC-14#2593]
## Description

When medical staff spawn in they start hungry the same as marines, so they have to walk to get food before doing anything else.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by diraven** [comment]
So what's the issue?

**Comment by Tunguso4ka** [comment]
They also spawn in cryo (should spawn)

**Comment by ShadowCommander** [comment]
Non-marine ship staff shouldn't spawn in hungry. In CM13, only the Marines come out of cryo hungry.

**Comment by Tunguso4ka** [comment]
yes, only marines starts with low nutrition:
```
/datum/job/marine/generate_entry_conditions(mob/living/carbon/human/current_human)
  ..()
  if(!Check_WO())
    current_human.nutrition = rand(NUTRITION_VERYLOW, NUTRITION_LOW) //Start hungry for the default marine.
```
