### ISSUE TITLE
GunDamageModifier is not applied until an extended barrel is attached at least once

### ISSUE THREAD

**Issue by snebl** [RMC-14/RMC-14#2646]
## Description

While testing weapons in the dev area i noticed that the extended barrel attachment seemed to have a damage increase that remains on a weapon even after you remove it.

Example: The battle rifle does 40 damage to a drone normally but will do 56 with an extended barrel HOWEVER a battle rifle with its extended barrel then removed also does the same 56 damage.

EDIT: I figured out that the assault rifle and battle rife are **supposed** to have a base damage increase. So the real issue is that this increase does not get applied at all unless you attach an extended barrel.

**Reproduction**

1.) Put an extended barrel on any applicable weapon
2.) Take it off
3.) Your weapon now deals more damage (the correct amount) despite now being identical to a fresh one 

**Screenshots**

![image](https://github.com/RMC-14/RMC-14/assets/96957003/583fa418-a329-47ec-99ed-b03c8563cee8)

**Additional context**

**Comment by Siigiil** [comment]
This appears to be a bug with the battle rifle itself not applying its +40% damage modifier. The extended barrel doesn't have a damage modifier, but attaching it causes the gun to properly apply its own, which then stays.

**Comment by snebl** [comment]
> The extended barrel doesn't have a damage modifier

Thats interesting. I assumed it was intended and almost mentioned how weird it was that the kind of substantial damage buff isn't mentioned in the attachment's description.

I should mention the assault rifle also got a damage buff when doing this AND that this bug seems to only happen with the extended barrel. The recoil suppressor had a damage reduction and something like a smart scope did not affect the damage.

**Comment by snebl** [comment]
Updated the issue a bit for clarity.
