### ISSUE TITLE
Dragging marines is too slow

### ISSUE THREAD

**Issue by Skarletto** [RMC-14/RMC-14#2677]
If you are not injured and wearing light armor, you should be able to carry marines pretty easily. This ain't the case, and instead takes forever

Subscract efficiency if you're in the water

**Comment by diraven** [comment]
Tried using rollerbeds?

**Comment by Skarletto** [comment]
Actually I got baited by pixel movement

RMC dragging with light armor is faster than CM dragging with light armor

https://github.com/RMC-14/RMC-14/assets/122584947/6756df5a-0644-451f-8ead-731d425a543d
