### ISSUE TITLE
Sniper sprite when held in suit slot doesn't rotate with player

### ISSUE THREAD

**Issue by TheDoctor1977** [RMC-14/RMC-14#2697]
## Description
See title.

**Reproduction**
1. Get weapon specialist sniper kit
2. Put on the ghillie armor and holster your sniper
3. Rotate
4. Weep

**Screenshots**
![image](https://github.com/RMC-14/RMC-14/assets/108845723/2c9f2111-4296-4e9d-a1b6-ef63e1dbf6cd)
![image](https://github.com/RMC-14/RMC-14/assets/108845723/be80c0b3-1c64-4969-84c1-d2c1d9b7c249)

**Comment by Dutch-VanDerLinde** [comment]
Fixed
