### ISSUE TITLE
Xeno Spit range is too short

### ISSUE THREAD

**Issue by Hmeister-real** [RMC-14/RMC-14#2699]
## Description
 It is too short and too underpowered to do anything of value, same with the scattered spit but less so

**Additional context**

**Comment by diraven** [comment]
Range of 6-7 tiles is likely intended and corresponds to [that of CM13](https://cm-ss13.com/wiki/Spitter).

**Comment by Tegotia** [comment]
This might be a thing that balances out better with bullet damage falloff, would let spitters get a bit closer without taking as much damage before closing

**Comment by Rainbeon** [comment]
Fixed by #4552
