### ISSUE TITLE
Nested storage hell

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [RMC-14/RMC-14#2702]
## Description
Some storage items allow you to place injectors and other medical items inside it, this allows you to store medical items extremely efficiently

![image](https://github.com/RMC-14/RMC-14/assets/151447893/cd4941e8-ac22-46b8-b627-528715d77717)
![image](https://github.com/RMC-14/RMC-14/assets/151447893/90ce43b9-7d7c-4058-b876-2fcb7345b8a7)

**Comment by Vermidia** [comment]
Should be fixed by #2790
