### ISSUE TITLE
Sentinel cannot use corrosive acid

### ISSUE THREAD

**Issue by c0rigin** [RMC-14/RMC-14#2710]

**Comment by Vermidia** [comment]
Can confirm this is the case. The times I played sentinel I can't use it at all.

**Comment by diraven** [comment]
Seems to work fine on dev server.

* Can't use how exactly?
* Does action start?
* Does action finish?
* Do you see acid on an object you tried to use it on?
* Which object did you try to acidify.

**Comment by Vermidia** [comment]
this was fixed by #2766
