### ISSUE TITLE
You shouldn't be able to shoot through fences

### ISSUE THREAD

**Issue by Skarletto** [RMC-14/RMC-14#2716]
People are building fences on top of cades and I think that's really dumb

**Comment by snebl** [comment]
Xenos would destroy the pathway from the landing pad to hydro every round and it also wouldn't make any sense.

> People are building fences on top of cades and I think that's really dumb

Why not rename to issue to that specific problem.

**Comment by Skarletto** [comment]
> Xenos would destroy the pathway from the landing pad to hydro every round and it also wouldn't make any sense.

Fences would be a problem for marines AND xenos. Not just one party

https://github.com/RMC-14/RMC-14/assets/122584947/3df50aff-8496-4ba1-b7a8-242c0f613210

**Comment by Vermidia** [comment]
https://github.com/cmss13-devs/cmss13/pull/6178
This got changed at some point in cm-13, so you uh, can shoot through fences apparently (afterwards fence hitpoints were nerfed to make them easy for xenos to destroy)

**Comment by Skarletto** [comment]
Correct, somehow. I don't know how my local testing didn't reflect this before (see the video I posted)

**Comment by Skarletto** [comment]
I was going to rename this issue to 'shouldnt be able to place on barricades' but fences were removed from build menu (lol)
