### ISSUE TITLE
Grenade shockwave and wanky camera view

### ISSUE THREAD

**Issue by UnicornOnLSD** [RMC-14/RMC-14#2725]
## Description

The grenade shockwave effect acts in a VERY weird way when it explodes and your camera rotation is not on the default axis
TL:DR it will for the time of the shockwave reset your camera abruplty to the normal axis then back

**Reproduction**

1. prime nade
2. change camera rotation (NUM 7 or 9)
3. wait for shockwave

**Comment by diraven** [comment]
I think it's already [fixed](https://github.com/RMC-14/RMC-14/pull/2807).

**Comment by UnicornOnLSD** [comment]
it do be now PR never mentionned it cheers
