### ISSUE TITLE
Almayer Medbay has regular medical HUDs mapped in various places instead of medical HUD glasses

### ISSUE THREAD

**Issue by TheDoctor1977** [RMC-14/RMC-14#2726]
Storage room in the north of the main bay
![image](https://github.com/RMC-14/RMC-14/assets/108845723/8b6bb902-efa7-4a16-908d-7ad3154a06e6)

South chemistry room
![image](https://github.com/RMC-14/RMC-14/assets/108845723/38e6910b-5ed8-4b9c-bade-ed95273fd04d)

There may or may not be more than these two, I didn't check very thoroughly.

**Comment by Tunguso4ka** [comment]
Is it still true?

**Comment by Tunguso4ka** [comment]
yeah, it is.
