### ISSUE TITLE
Larbas can sometimes spawn behind walls if the spawner marine is stuck to them

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#2772]
![image](https://github.com/RMC-14/RMC-14/assets/155400926/4ed98637-fcfa-4f84-aad7-90f4052804da)

Unsure how to replicate

**Comment by Tegotia** [comment]
I've witnessed several incidents that required admin intervention to fix otherwise the player would be stuck forever, possibly stalling the round (in the case of one stuck immature queen).

**Comment by ARMOKS** [comment]
Figured it out, when warriors punch a host it launches them into the wall.

**Comment by ARMOKS** [comment]
Fixed by the warrior punch fix
