### ISSUE TITLE
Warriors can break weeds with punch ability

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#2775]

**Comment by dolgovmi** [comment]
they can also charge to said weeds

**Comment by Derrek-Larson** [comment]
Working on this, should have a PR up soon.

**Comment by Derrek-Larson** [comment]
Also confirmed, Woya can target many entities (including floorweeds and wall weeds) with its leap.

**Comment by DrSmugleaf** [comment]
Fixed in https://github.com/RMC-14/RMC-14/pull/2897
