### ISSUE TITLE
Crusher charge can send you past barricades

### ISSUE THREAD

**Issue by vorkathbruh** [RMC-14/RMC-14#2780]
## Description

Crusher charge can send you past functional barricades, seems to work from either side of a barricade.

**Reproduction**

With the Crusher's charge ability, select a tile near past the barricade that you wish to go to. You will land on the opposite side rather than stopping after colliding with the barricade. Does not seem to occur every time.

**Screenshots**

**Additional context**

https://github.com/RMC-14/RMC-14/assets/152932728/7784bfa6-02eb-44bf-9721-ceddf5881fed

**Comment by Mattshark89** [comment]
I believe this was just fixed: https://github.com/RMC-14/RMC-14/pull/2889

**Comment by Zarq0** [comment]
Agreed, can be closed since the pr is merged.
