### ISSUE TITLE
Rules and locale contradict for chain of command

### ISSUE THREAD

**Issue by dffdff2423** [RMC-14/RMC-14#2798]
Here it states that the SO is next in line after the XO.
https://github.com/RMC-14/RMC-14/blob/master/Resources/Locale/en-US/_RMC14/job/command.ftl#L7 

However, in the rules it states that the ASO is third in line with the SO being much further down (this is also what is on the CM13 wiki):
https://github.com/RMC-14/RMC-14/blob/master/Resources/ServerInfo/Guidebook/_RMC14/Rules/Roleplay/CMCommandChain.xml

**Comment by Skarletto** [comment]
where does it state SO is next in line? all this says is

> Monitor the marines, man the CIC. In charge of logistics and the overwatch system.

which refers to the role this job fills
generally, you get 4 SOs per round (or more if they cryo), 1 for each squad, and they oversee said squad, relaying information to the commander. They normally have access to helmet cameras and a live tacmap to collect information from the battlefield. That's what manning the CIC and being in charge of the overwatch system refers to. 

As for logistics, SOs have the possibility to dial an OB (orbital bombardment) and dial coordinates for a supply drop (in tandem with Req).

Obviously, none of this is currently implemented in RMC14

I don't see where it says they're next in line. The only relevant sentence is 

> You are second in command aboard the ship, and are the next in the chain of command after the Commanding Officer.

Which only refers to the Captain

**Comment by TheDoctor1977** [comment]
The SO page on the CM13 wiki says:
>Staff Officers (SO) are sixth in command after the Auxiliary Support Officer (ASO), Chief MP (CMP) and Chief Medical Officer (CMO). Despite being the 6th in line for Command, generally when there is no CO, XO, or ASO, the role of Acting Commanding Officer will pass down to you since other department heads are too busy in their own department.

So, officially, 6th. Unofficially, 4th.

**Comment by dffdff2423** [comment]
Seems this was fixed here:
https://github.com/RMC-14/RMC-14/commit/656fafd89613b2597c94f81b1659739599562697
