### ISSUE TITLE
Sandbag barricades shouldn't be unanchorable

### ISSUE THREAD

**Issue by Skarletto** [RMC-14/RMC-14#2823]
the point is it's a quick cade to place down if you need

you can deconstruct it with an entranching tool or a shovel

moving a stack of bags like you could with a normal barricade is silly

**Comment by UnicornOnLSD** [comment]
yeah but what if I rotate it wrong and I unanchor it from the ground with it's imaginary bolts to set it right >:( (valid issue)

**Comment by Skarletto** [comment]
you shovel it and place it again (skill issue)
