### ISSUE TITLE
a few of the tiles on the cargo elevator are plating

### ISSUE THREAD

**Issue by deltanedas** [RMC-14/RMC-14#2840]
## Description
not metal floor (no weeds)
should be easy to fix when editing almayer

![11:16:52](https://github.com/RMC-14/RMC-14/assets/39013340/e5c147bf-4234-41a0-a8ea-465f682625d2)

**Comment by QuietlyWhisper** [comment]
I think this is caused by damaging the tiles, but I remapped the tiles anyway
