### ISSUE TITLE
Hijack sometimes ends up having both ships at once

### ISSUE THREAD

**Issue by SphiraI** [RMC-14/RMC-14#2845]
## Description
Rarely, as the xeno's are about to hijack, both dropships will appear on one LZ, possibly gibbing anyone there, while also causing issues with both ships landing on the same crash-point on the mothership. And if the landings are delayed for whatever reason, it can cause multiple gibbings out of thing air.

**Reproduction**
Unknown, best guess would be one ship going planetside as the queen calls one down

**Additional context**
It's only happened twice now (to my knowledge), but causes a lot of random, buggy death.

**Comment by Mattshark89** [comment]
I've had it happen once when I accidentally spammed E on the console, causing two popup messages to appear. Perhaps spamming the console can reproduce it?

**Comment by Vermidia** [comment]
Fixed by #3177
