### ISSUE TITLE
Almayer really needs temporary fax machines

### ISSUE THREAD

**Issue by TheDoctor1977** [RMC-14/RMC-14#2860]
Currently, there are none. While I understand they will come with the second floor and CIC/CL office, they are very much needed now. From what I have seen, admins are manually spawning them, but this is obviously not sustainable for however long it takes to develop the second floor.

I feel as though a suitable place for them would be in the room where the Groundside Operations Terminal is temporarily located, perhaps just to the sides of the terminal.
![image](https://github.com/RMC-14/RMC-14/assets/108845723/3779a60a-2751-410c-966f-b09dfb7a7ecf)

**Comment by Tunguso4ka** [comment]
Done!
Thank you Smug <3
