### ISSUE TITLE
Comedically horrendous lag with seemingly no clear cause

### ISSUE THREAD

**Issue by TheDoctor1977** [RMC-14/RMC-14#2864]
## Description
Every 5-10 minutes, typically during combat (though this may be coincidence) I get the worst lag I've ever had playing SS14. Like, in the attached video, when I'm stuttering left, I had been holding right for like 15 seconds. This mainly happens as a xeno, but I also experience it (less frequently) as a marine.

**Reproduction**
I genuinely have no idea.

**Screenshots**
Video was too big for git. 
https://streamable.com/b898dl
(apologies for the shitty audio, had to compress it a bit)

**Additional context**
It might be related to a large amount of bullets or particles on screen? Queen was moving with a lot of crushers and we all stomped at once, plus the shitload of grenades, but again it occurring during combat may just be a coincidence because I was almost always in combat.

**Comment by DrSmugleaf** [comment]
Does this happen to other people at the same time? If so it could be grenades hitting many (like 50+) things at once, if not it would be something else. Next time it happens ask in LOOC if it just happened to someone else, or watch if anyone else says something about it at the same time.
Not sure how to begin diagnosing this but one thing would be to check the console (tilde) for any error spam happening.
What are your PC's specs? CPU, GPU, memory, OS, etc

**Comment by Draxian** [comment]
I'm also experiencing this issue every 30 minutes or so. It's unclear if it's related to CM14 or my ISP, as I experience packet loss (100% for a few seconds) in other games like Valorant.

**Comment by snebl** [comment]
I get very similar lag spikes every 15-30 minutes in bursts of 2. I have a good system and it doesn't happen to me on any other ss14 server. It feels less like lag and more like being disconnected (rubber banding to the same position for like 2-5 seconds with inputs like pointing only handled after the 'spike' stops).

**Comment by TheDoctor1977** [comment]
> Next time it happens ask in LOOC if it just happened to someone else, or watch if anyone else says something about it at the same time.

Every time it happens I say something in LOOC and nobody else does, so it seems to be just me.
> What are your PC's specs? CPU, GPU, memory, OS, etc

CPU: Intel Core i5-0400F
GPU: Nvidia RTX 2070 Super
Mem: 16gb total
OS: Windows 10

**Comment by snebl** [comment]
i don't know what changed but my lag spikes went away like two updates ago

**Comment by TheDoctor1977** [comment]
Yeah, this is no longer reoccurring it seems.
