### ISSUE TITLE
Xenos should need to be full health to evolve

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#2867]
## Description

Devolving and Evolving should require full health. I checked CM13 and a Xeno needs to be full health to evolve there. Otherwise lower tier xenos can save their evolve for a free (after a small doafter) heal.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Mattshark89** [comment]
I believe this has been already fixed: https://github.com/RMC-14/RMC-14/pull/2805

**Comment by Vermidia** [comment]
That's for devolving. Evolving atm does not need full health
