### ISSUE TITLE
CMO, Doctors and Nurses should spawn in cryo

### ISSUE THREAD

**Issue by Tunguso4ka** [RMC-14/RMC-14#2883]
## Description

There are a room with hypersleep chambers above med called "Lower Deck Conference Office". In cm-ss13 there are markers for CMO, Doctors, Nurses, Researchers, OTs and MT.

Right now they spawn in med.

![зображення](https://github.com/RMC-14/RMC-14/assets/71643624/ba26bfff-f4e7-4a2a-8f23-f767bf302ccd)

**Comment by QuietlyWhisper** [comment]
fixed in next update
