### ISSUE TITLE
BUG: Xeno eggs can be placed under doors

### ISSUE THREAD

**Issue by UnicornOnLSD** [RMC-14/RMC-14#2903]
## Description

Xeno eggs can be placed under doors. It shouldn't and leads to some very dirty gameplay for players that abuses it.
You get an invisible trap that will stun for 90s any humanoid near it without them having a way to tell.

**Reproduction**

Be Xeno
Grab egg
Place under open door
Door closes

**Screenshots**

![image](https://github.com/RMC-14/RMC-14/assets/149102472/3ff61e29-4105-4e61-b935-a7ae6a61a3cc)

**Additional context**

I would assume it's because it just anchors in an empty spot and doesn't check is any structure is already there.

**Comment by Verification31** [comment]
I know this is fixed for resin structures, but I dont think it is for marine doors. I saw two eggs placed underneath both sides of a doubledoor.
