### ISSUE TITLE
Xenos can toggle IVs (and possibly other right-click human interactions)

### ISSUE THREAD

**Issue by Mattshark89** [RMC-14/RMC-14#2909]
## Description

Xenos can right-click-dropdown interact with certain human things. I noticed this with blood IVs but haven't tested any other items.

**Reproduction**

- Right-click an IV as a xeno
- Click the Toggle button (in the right-click popup)
- The IV will now draw blood rather than inject it

**Screenshots**

![image](https://github.com/RMC-14/RMC-14/assets/32344718/e965b084-15ba-4624-b590-58d73ba6d0ae)

**Additional thoughts**

Is this really a problem? Dunno, lurkers sabotaging IVs could be funny. I do assume this may cause problems with future items however. Xenos aren't supposed to touch human things.

**Comment by Kadeo64** [comment]
it's possible to alt click on lamps and stuff to toggle them, as well as buckling humans to beds
