### ISSUE TITLE
RMC14: The consequences of technology update

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#2924]
XENOMORPHS CAN WATCH TV (and translate what talls are saying with it) They can also use intercomms to speak with talls.

**Comment by ARMOKS** [comment]
![image](https://github.com/RMC-14/RMC-14/assets/155400926/b1b9b1eb-dca1-4d34-9c92-9d8ba1b5ccae)

**Comment by deltanedas** [comment]
the reverse is true too, xenos can speak into a camera and be understood

**Comment by ARMOKS** [comment]
Fixed
