### ISSUE TITLE
M276 Pattern Lifesaver bag still have abysmally long UI's

### ISSUE THREAD

**Issue by SphiraI** [RMC-14/RMC-14#2932]
## Description
Title.

**Reproduction**
- Grab M276 Pattern Lifesaver bag (`CMBeltMedicBagFilled`)
- Open it
- Deal with a second bar as long as your action-bar that you may or may not be able to fully see due to screen size.

**Screenshots**
*taken on a live server on 7/9/2024*

Aforementioned bag
![image](https://github.com/RMC-14/RMC-14/assets/145869023/e79bb7b6-ee80-48cf-8568-68c8d9543989)

Normal medical belt with original fix working
![image](https://github.com/RMC-14/RMC-14/assets/145869023/1b5bf7bf-61be-46fc-b720-4e15b0793a81)

**Comment by DrSmugleaf** [comment]
Fixed in https://github.com/RMC-14/RMC-14/pull/2912, waiting for the update for it to be live
