### ISSUE TITLE
Corrosive acid rework

### ISSUE THREAD

**Issue by diraven** [RMC-14/RMC-14#2952]
From CM13: https://github.com/cmss13-devs/cmss13/blob/b72dc18a26d2f4b5072d2b65145d6130036e0755/code/game/objects/effects/aliens.dm#L283:
* Weak acid: 2.5 delay, 20 barricade damage, 150 flare damage (-15 seconds).
* Strong acid: 0.4 delay, 100 barricade damage, 1875 flare damage (-187.5 seconds).
* Medium acid: 1 delay, 40 barricade damage, 500 flare damage (-50 seconds).
* delay - multiplier that is applied to tick length. *(wtf is that parameter name...)*
* There also different types of meltables, apparently, not just "meltable" and "unmeltable". There is also "strong" that can only be melted by strong acid and takes more time.
* Damage (or fuel) unit for flares seems to equal 0.1 second. So flare burning for 10 minutes equals 6000 fuel or 6000 damage units.

Melting works roughly like the following:
* Flares:
  * Ticks happen every  `random(15, 25) * acid_delay` seconds subtracting flare damage until fuel (essentially, timer on a flare) runs down to 0.
* Barricades:
  * Ticks happen every 5 seconds.
  * Acid subsides during weather events.
  * Barricade damage is applied to barricade directly until it's destroyed. Damage modifiers are applicable.
* Other objects:
  * 9 ticks assigned to the object.
  * Every tick is `random(20, 30) * acid_delay` seconds long.
  * Once amount of ticks reaches 0 - object is destroyed.
  * Messages appear at certain ticks to signify how melted the object is.
* Walls (they call it turf, apparently):
  * Same as other objects, but there are 7 ticks rather then 9.
  * There is a comment that walls take twice the time to melt, but I didn't see that in the code. If comment is true - there would be 14 ticks for walls. Whoever played the game might know better.

That should be enough to implement melting like in CM13.

- [x] Adjust timers for regular object to be the same as CM13.
- [x] Implement flares interaction with acid.
- [x] Implement barricades interaction with acid.

**Comment by diraven** [comment]
I don't really understand the need for those random parts. In 9 random checks it's extremely unlikely for the value to significantly deviate from average. Could just use 20 seconds per tick for flares and 25 seconds per tick for other objects. Result would be roughly the same and the difference won't matter much for gameplay purposes. I very much doubt anyone would be counting seconds to any object destruction and putting timer to not miss it.

So if we go that way and simplify:
* Objects should melt in 9.375 minutes with weak acid, 3.75 minutes with normal acid and 1.5 minutes with strong acid.
* Walls should melt in 7.2916 minutes with weak acid, 2.9166 minutes with normal acid and 1.16 minutes with strong acid.
* For flares we can just calculate how much fuel will acid take over the time flare has left to burn and subtract that from the timer and be done with it. No need for ticks.
* Barricades will have to remain tick based since they can be damaged while melting and require acid to apply damage gradually.

One unanswered question that I still have is whether barricades can be repaired while being melted.

**Comment by diraven** [comment]
Barricades being melted can be deconstructed returning 4 pieces of steel. Should probably not be the case.

**Comment by diraven** [comment]
Deconstracting metal barricade gives full cost of 4 metal back. Destruction only gives 2 metal back. Corroded object gets deleted completely without any return. With new approach it's going to leave 2 sheets of metal, since we'll be using regular damage process, not "delete after timer expires" approach.

I'm not quite sure how it works on CM13, so will just go the most obvious way for now, we can refine this later:
- Barricades being corroded can not be deconstructed.
- Barricades being corroded yield no return materials on destruction.

If anybody knows how this functions in CM13, let me know.

**Comment by diraven** [comment]
Apparently, objects being corroded can be picked up and are perfectly functional. It's kind of funny to pick up a weapon and use it before it corrodes in your hands... I'm just not sure if it makes much sense.

I see 2 problems with this:
* If you pick up a stack of any material that is being corroded - you can split it and then merge it back to create a new stack. And corrosion will be gone.
* Metal that is being corroded can still be used perfectly fine to e.g. build barricades or craft something. Final product  will not being corroded any more.

Easiest way to fix this would be just prevent pick up of objects that are being corroded with a message and a bit of burn damage. But then the corrosion timer on e.g. guns doesn't make much sense outside of immersion since the gun will become unusable the moment it has acid on it.

**Comment by deltanedas** [comment]
realistically a gun has many moving parts and with enough corrosion wouldnt be able to fire long before it fully melts

stacks like metal should slowly lose stacks until disintegrating, and there is an event it can use (fultons upstream do this to keep it linked when splitting) to have corroded stacks stay corroded with split

**Comment by diraven** [comment]
I'm curious how CM13 deals with stacks. I did not see anything in the CM13 code that would make stacks any different then any other objects, so pretty much timed destruction. What I'm not sure is whether you can pick those stacks up and split them or build with them.

**Comment by diraven** [comment]
Apparently, cm13 doesn't care much. Stacks can be picked up, then split and acid will go away. So will leave that bit of the functionality as is, it's close enough to what rmc14 does.

**Comment by diraven** [comment]
Acid costs: https://github.com/cmss13-devs/cmss13/blob/b72dc18a26d2f4b5072d2b65145d6130036e0755/code/modules/mob/living/carbon/xenomorph/abilities/general_abilities.dm#L144

**Comment by diraven** [comment]
Flares damage:
* Weak acid: 2.5 delay, 20 barricade damage, 150 flare damage (-15 seconds), ticks every 50 seconds.
* Medium acid: 1 delay, 40 barricade damage, 500 flare damage (-50 seconds), ticks every 20 seconds.
* Strong acid: 0.4 delay, 100 barricade damage, 1875 flare damage (-187.5 seconds), ticks every 8 seconds.

Average acid flare degradation speed:
* Weak acid: 18 seconds per minute, 0.3 dps.
* Medium acid: 150 seconds per minute, 2.5 dps.
* Strong acid: 1406 seconds per minute, 23.4375 dps.

Final formula: $`x=b/(a+1)`$ where:
* x - life expectancy of the acidified flare.
* b - time left on the flare before acidification.
* a - acid flare dps.

So timer on the freshly deployed flare (600 seconds remaining) if it was immediately acidified with weak acid must be changed to 461.5 seconds, for normal acid it would be 171.4 seconds, for strong 24.6 seconds.

Timer on half-burned flare (300 seconds remaining) must be changed to 230 seconds for weak acid, 85.71 for normal and 12.28 for strong.

**Comment by diraven** [comment]
Decided to not deal with deconstruction and not spawning materials on destruction for now, for simplicity's sake. This is already closer to cm13 then current system anyways. We can refine it further later. One thing at a time.
