### ISSUE TITLE
Evolving near a fence lets you walk over climbable objects without climbing them for a long time

### ISSUE THREAD

**Issue by Juan0045** [RMC-14/RMC-14#2962]
## Description
 When evolving from a drone to hivelord near a fence, I glitched onto the fence without climbing it, and after that i was able to walk over any climbable surfaces for a really long time without any need to climb, i was unable to interact with tables or fences (alt +click to climb them did not work, i could still attack and break them), eventually it fixed itself no idea at what point or how long exactly it lasted, but it lasted for a good 5 minutes minimum potentially longer, unsure how as i wasn't constantly near climbable surfaces to test this and avoided abusing it, I also did not get to test if it worked on barricades, i assume it does but it stopped happening to me before i was able to encounter any and i wanted to avoid abusing it.

**Reproduction**
1. Be drone
2. find a horizontal fence (potentially any fence not sure)
3. Stand right up against it, i was facing down towards the fence from the northern side
4. Evolve into hivelord
5. Appear on the fence when you evolve
6. Walk over any climbable like tables or fences, you can walk away and it will persist for a while

**Screenshots**
n/a

**Additional context**
I Ahelped it mid round and it happened to me during Round 310 near the center of the map as soon as hivelord was available to the hive

**Comment by Rainbeon** [comment]
This occurs even after even any normal vaulting, allowing you to phase through any barricades for a very long period afterward, even if unattached to the original. (INCLUDING Barbed Wire barricades)

**Comment by Juan0045** [comment]
Closing because this is basically a dupe of #3031 and that one has better information.
