### ISSUE TITLE
The toolbelt rigs you get in vendors should be filled

### ISSUE THREAD

**Issue by Skarletto** [RMC-14/RMC-14#2966]
![image](https://github.com/RMC-14/RMC-14/assets/122584947/1568e01a-4390-403b-8a95-93c6b9217aca)

**Comment by Skarletto** [comment]
![image](https://github.com/RMC-14/RMC-14/assets/122584947/1568e01a-4390-403b-8a95-93c6b9217aca)

**Comment by DrSmugleaf** [comment]
Combat or non-combat? The combat ones seem to vend empty in 13, and we already filled the non-combat ones, unless it was fixed after this issue was opened.

**Comment by Skarletto** [comment]
Yes, I believe this was fixed after I made the issue
