### ISSUE TITLE
meralyn recipe doesnt work

### ISSUE THREAD

**Issue by JoeHammad1844** [RMC-14/RMC-14#2979]
## Description

i didnt get a screenshot but i used bicaridine from a bottle, carbon from a dispenser and water from a sink in surgery, the recipe just refused to work

**Comment by QuietlyWhisper** [comment]
The actual issue is that the recipe uses RMC water and the sinks and bottles hold ss14 water, so we need to choose which we're actually using and update those prototypes

**Comment by JoeHammad1844** [comment]
bruh.
oh by the way you need to run a migration to turn all rollerbeds into CM rollerbeds because ALL OF THE ONES IN MED are the SS14 ones that dont fit in rig belts/first responder pouches

**Comment by QuietlyWhisper** [comment]
true
 I'm gonna pr removing rmc water and just change the color of upstream
