### ISSUE TITLE
Coremen default satchel has incorrect cross

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [RMC-14/RMC-14#2985]
## Description
the uniform still has a green cross and not a blue one

![image](https://github.com/RMC-14/RMC-14/assets/151447893/cf9d8cfa-5f66-42a3-985e-9895d0f750bb)

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
I figured out where the green cross is, its on the default medic satchel

**Comment by Hyenh** [comment]
Resolved. #3568
