### ISSUE TITLE
Actually, something is wrong with Queen's screech

### ISSUE THREAD

**Issue by Mattshark89** [RMC-14/RMC-14#3000]
## Description

Something's been bugged since the screech wall penetration PR https://github.com/RMC-14/RMC-14/pull/2866

In some cases it seems to be blocked by... nothing?

**Reproduction**

See video below

**Screenshots**

https://github.com/user-attachments/assets/a8b1b2b1-23f7-4ea1-8569-20eb25e4f375

**Additional context**

I can still hug the marines, so `InRangeUnobstructed` should be resulting to `true`.

**Comment by Mattshark89** [comment]
...Y'know, I think I found the cause, and given its severity I'll call @DrSmugleaf directly into this one.

I think... marines are considered Opaque. 💀 

https://github.com/user-attachments/assets/43e3b20b-1a72-427c-ad2f-4575ed201d80

**Comment by DrSmugleaf** [comment]
> I think... marines are considered Opaque. 💀

Incredible
Apparently so, so the fix is checking that any blockers are both Opaque and Impassable I think, I don't know if the flag in InRangeUnobstructed checks that something is both or either, but at worst you can pass in your own Ignore predicate.

**Comment by Mattshark89** [comment]
I've just finished experimenting with `InRangeUnOccluded` as an alternative to `InRangeUnobstructed` (used in ninja dash) right now. It appears to work exactly as expected, even fixing the weird windows-being-blockers issue.

However, that is borrowed from the Examine System (Shared) rather than the Shared Interaction System, so I'm unsure if using it can be considered good practice.

https://github.com/user-attachments/assets/c01579be-865c-4896-8139-c538f2f7ec33

I'll save this fix off to the side so I can experiment with Unobstructed more.

**Comment by DrSmugleaf** [comment]
> Or if you want the UnOccluded fix, let me know and I'll get a PR up.

Sounds fine, I'd need to check the code but if you can't find any edge cases it's probably ok

**Comment by Mattshark89** [comment]
fixed by https://github.com/RMC-14/RMC-14/pull/3002
