### ISSUE TITLE
We-Ya and High command faxes are non-existent

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#3013]
they should be added

**Comment by diraven** [comment]
Seems to be taken care of: https://github.com/RMC-14/RMC-14/issues/2860

**Comment by Dutch-VanDerLinde** [comment]
> Seems to be taken care of: #2860

no, the fax machine exists, there are no we-ya or high command faxes

**Comment by Tunguso4ka** [comment]
there are `CMFaxWY` and `CMFaxHighCom` in `Resources/Prototypes/_RMC14/Entities/Structures/Machines/fax_machine.yml`

**Comment by Dutch-VanDerLinde** [comment]
> there are `CMFaxWY` and `CMFaxHighCom` in `Resources/Prototypes/_RMC14/Entities/Structures/Machines/fax_machine.yml`

you can't fax to them

**Comment by Tunguso4ka** [comment]
> you can't fax to them

ah, you mean that there are no faxes ingame.

**Comment by Zarq0** [comment]
iirc the faxes have to be spawned in manually by admins so yeah

**Comment by Tunguso4ka** [comment]
Done.
