### ISSUE TITLE
Parasites should use impregnated sprite instead of dead sprite when they die from infecting

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#3023]
## Description

When dying after an infection, parasites right now will use a dead sprite, instead of using the impregnanted sprite we have.

Makes it easier to tell if a parasite actually died or if it just infected someone.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
likewise it also makes a xeno death announcement when it should either:
- not announce since an infection is good as opposed to a suiciding marine-controlled parasite
- announce they infected someone

**Comment by Dutch-VanDerLinde** [comment]
Fixed

**Comment by Vermidia** [comment]
yep
