### ISSUE TITLE
reinforced walls don't yield their materials when deconstructed

### ISSUE THREAD

**Issue by UnicornOnLSD** [RMC-14/RMC-14#3038]
## Description

it takes 3 steel (2 and two rods) and 5 plasteel to make one, while deconstructing it gives no plasteel at all and a rod with 2 steel 
**Reproduction**

make reinforced wall
decon reinforced wall
materials gone, day ruined 
**Screenshots**

**Additional context**

**Comment by Siigiil** [comment]
Not a bug. This is how it works in CM13. If we change this, it will likely be after we're done with porting.
