### ISSUE TITLE
Auto-injector and pill bottle labels should look how they do in CM13

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#3051]
## Description
Currently, the text labels for them fill up basically the entire item sprite and look really ugly

**Screenshots**
In RMC14:
![image](https://github.com/user-attachments/assets/e1ee77dc-05ab-411e-9bb9-fb23c7f52061)

In CM13:

![image](https://github.com/user-attachments/assets/dcc297dc-3ceb-4e4d-9bb9-0e9b6e57a656)

**Additional context**

**Comment by Siigiil** [comment]
Has since been fixed.
