### ISSUE TITLE
Knife damage in stomach is too high

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#3076]
## Description

Currently devoured marines do too much damage and are slightly faster(? could be the same but it's hard to tell) compared to CM13 that it isn't viable to devour anyone who isn't critical.

In CM13, a drone, on weeds, no pheromones, can keep someone in their stomach for about a minute with constant knife attacks as fast as possible, before dying/spiting them out. Some castes like defenders will even have some health remaining. Crushers barely take any damage (like 1:3 or 1:4 of health) at all before regurgitating.

In RMC14, almost 20 seconds and you can be killed with a combat knife in the same circumstances (Drone, on weeds, no pheromones). Defender can make it to about 40 before being crit, and by almost a minute is dead. Crushers make it to critical by the time regurgitation runs out.
**Reproduction**

**Screenshots**

**Additional context**

**Comment by Siigiil** [comment]
The knife damage thing is a bug caused by some attachment melee modifier code. It's fixed in the WIP attachments PR.

**Comment by Vermidia** [comment]
Good to know

**Comment by Siigiil** [comment]
Knife damage will be restored to normal once #3197 is merged. Not tagging it as closing this, as we might need to make more changes.

**Comment by Vermidia** [comment]
Should be fixed by #3259
