### ISSUE TITLE
Smart gun bullets are backwards

### ISSUE THREAD

**Issue by ShadowCommander** [RMC-14/RMC-14#3084]
## Description

**Reproduction**

**Screenshots**

![reverse-sg-bullet](https://github.com/user-attachments/assets/da702549-8387-4d65-9737-3f2c667aa9c0)

**Additional context**

**Comment by DrSmugleaf** [comment]
God dammit
Also they are supposed to be more red, not sure which texture it is exactly

**Comment by Vermidia** [comment]
Fixed in #3169
