### ISSUE TITLE
Xeno Queen can cause Nuclear Fusion

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#3107]
## Description
Xeno queens can somehow call both the marines shuttles at the same time to the same LZ, causing some strange things to happen.

**Reproduction**
Unsure, occurred near the end of Round 412

**Screenshots**

![image](https://github.com/user-attachments/assets/93a7bab2-f9a1-465b-807e-2d55dcf3c962)

**Comment by MACMAN2003** [comment]
where's pauli and his exclusion principle when you need it most

**Comment by ARMOKS** [comment]
Fixed
