### ISSUE TITLE
Crusher Stomp pierces walls

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#3108]
Damages marines through walls, simple as

**Comment by Vermidia** [comment]
intended

**Comment by ARMOKS** [comment]
> intended

I would argue it should be unintended then because it is quite simply unfair to marines

**Comment by ARMOKS** [comment]
I can just camp outside their fortifications with 0 risk and drain their meds

**Comment by Mattshark89** [comment]
Don't stand against the walls
