### ISSUE TITLE
Objects will be placed titled if you click on a table with it

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#3110]
![image](https://github.com/user-attachments/assets/42585d7e-8f1d-445d-993c-9fa7b340de6d)

Placed a figure on a table and it came out like this

**Comment by B1essedknight** [comment]
With the drop key or by just clicking the table with the object in hand?

**Comment by Dutch-VanDerLinde** [comment]
> With the drop key or by just clicking the table with the object in hand?

click

**Comment by Dutch-VanDerLinde** [comment]
fixed with upstream merge? someone should check
