### ISSUE TITLE
B12 Armor doesnt have the slowdown of light armor

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#3113]
The entire point of purchasing this armor is for medium protection with light speed but it seems to have medium protection medium speed.

**Comment by Dutch-VanDerLinde** [comment]
pretty sure it has heavy protection, with medium speed, and extra pockets

**Comment by Dutch-VanDerLinde** [comment]
> pretty sure it has heavy protection, with medium speed, and extra pockets

heavy armor has 25 armor and 25 explosion armor
b12 has 25 armor and 20 explosion armor

**Comment by UnicornOnLSD** [comment]
yes, B12 is medium slowdown for heavy armor physical resistance, the one that could use some love is the M4 which is objectively garbage (medium armor with extra mag slot)

**Comment by Dutch-VanDerLinde** [comment]
yea, maybe the M4 is medium armor with light slowdown and extra pockets, sidegrade to the B12 rather than being worse

**Comment by krose124** [comment]
https://cm-ss13.com/wiki/Marine_Equipment#Military_Armor
The B12 has the slowdown of medium armor with medium armor and slightly better explosive armor.
This is currently how the B12 is implemented, 
armor (bullets physical damage etc.) -> 25
explosive armor -> 20
speed mult -> .727 (medium speed)

For context normal medium armor,
armor -> 20
explosive armor -> 15
(same speed as B12)

I get that the description of the B12 says it is for quick movement, but the CM13 wiki does not back this up. The stats on the wiki show the B12 as being a more protective medium armor with the same speed.

**Comment by krose124** [comment]
For even more context with armors,
The EOD (the heavy marine armor) has the same normal armor as the B12, but the EOD has more explosive armor and a slower movement multiplier.

The exact numbers for the EOD,
armor -> 25
Expl armor -> 35
movement mult -> .68

**Comment by Siigiil** [comment]
Both medium and B12 have `SLOWDOWN_ARMOR_MEDIUM` as their move delay modifier. This isn't a bug.
