### ISSUE TITLE
you can get infinite backpacks through the comtech vendor

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#3118]
![image](https://github.com/user-attachments/assets/8cdf972c-33fb-4350-893c-9aaf2bfdb294)

it doesn't grey out when you select one and you can spawn an infinite amount

**Comment by UnicornOnLSD** [comment]
extending this to gas masks and coifs too, it don't grey out and boom suddenly the vendor is covered in it
