### ISSUE TITLE
Primary LZ

### ISSUE THREAD

**Issue by Kaga-404** [RMC-14/RMC-14#3127]
## Description

Maps and mechanics are designed around a primary LZ, which can be picked by Command within the first 25 minutes of a round, and then is forcefully set at 25 minutes to LZ1.

Queens can only interact with the Primary LZ computer to call dropships down. This doesn't prevent hijacking if the non-primary dropship lands anyway, which works fine with RMC since either dropship can go to either LZ already.

**Reproduction**

**Screenshots**

**Additional context**

Relevant Code:
colonialmarines.dm ln183: Sets LZ1 if active_lz is not yet set.
communications.dm ln320: Option in the CIC communications console to set the Primary LZ
groundside_operations.dm ln70, ln259: XO/CO console can also set it.
human.dm ln105: Marines are meant to know which LZ is the primary in their Status panel, but not sure where that'd fit in SS14 UI.
**dropship_computer.dm ln181:** External dropship consoles. Prevents calling down before first drop, and if not Primary LZ. 1/2 of the ported solutioned needed to remove LZ turrets as well, the other part being invisible weed blockers on a timer.
dropship_computer.dm ln353: These consoles are also present on the marine ship, and can be used to set autopilot and stuff. This line also includes the primary LZ in the console.
**shuttle_console.dm ln236:** The actual consoles inside each dropship. Technically can be placed outside of a dropship, but if it's not onboard a dropship and isn't the primary LZ, should also fail just like the proper LZ consoles (dropship_computer.dm). This isn't needed if there's no plans to reuse the dropship consoles outside of the dropships.

**Comment by Vermidia** [comment]
Implemented by #3177
