### ISSUE TITLE
ColMarTech automated munition vendor has shells in the wrong place

### ISSUE THREAD

**Issue by TheDoctor1977** [RMC-14/RMC-14#3130]
They are under "Regular Ammunition", when there is an empty "Shotgun Shell Boxes" category at the bottom.
![image](https://github.com/user-attachments/assets/41db9954-2504-4b34-8a52-2479dcab7343)
![image](https://github.com/user-attachments/assets/5ff7f433-474d-40d8-bb54-171d8ddfe756)

**Comment by DrSmugleaf** [comment]
This is intended, that section is for magazine boxes, we are just missing them 
![image](https://github.com/user-attachments/assets/c12afe8f-b169-4be6-bc6b-75f8489dcb45)
