### ISSUE TITLE
Gun size mania

### ISSUE THREAD

**Issue by UnicornOnLSD** [RMC-14/RMC-14#3150]
## Description

It's been reported three times on the discord now, because of how gun size is calculated now, it seems you can fit guns in ridiculous spaces where you shouldn't
**Reproduction**

have gun
try to put it in helmet
works ?
try to put a long shotgun in webbing
works ?
**Screenshots**

![image](https://github.com/user-attachments/assets/b03136d2-6fb1-4aed-ad4d-3eabea83dbf7)
![image](https://github.com/user-attachments/assets/85aec7e1-9dc7-4abc-9de9-d654bf231bce)
![image](https://github.com/user-attachments/assets/4c6b2f0f-e7ed-4dfc-9a4d-cb3299a71e3a)

**Additional context**

it's 100% linked to how gun size is now calculated based on attachments it has, with #2788

**Comment by deltanedas** [comment]
specifically caused by adding a stock

**Comment by Siigiil** [comment]
#3197 seems to have fixed this. At least I couldn't reproduce it in the round I played earlier today, and there haven't been any new reports. So I'm reasonably certain it's gone.
