### ISSUE TITLE
Pulling a character that just died will cause strange behaviour

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#3199]
- pull a crit character
- they die while you're pulling them
- the game thinks you are pulling them, but you are not
- stop pulling
- get teleported back to the dead character's position

**Comment by MACMAN2003** [comment]
i've noticed this on upstream as well

**Comment by Dutch-VanDerLinde** [comment]
Re-open the fix was reverted

**Comment by Dutch-VanDerLinde** [comment]
https://github.com/space-wizards/RobustToolbox/pull/5372

I think this was fixed by this pr not sure

**Comment by metalgearsloth** [comment]
Contacts shouldn't be affecting this kind of issue, if anything it's a fault setting cancollide on something with joints (it was probably the stuff to make dead bodies still collidable that fixed it).
