### ISSUE TITLE
The bag option in colmartech should be a one-time use only like every other option

### ISSUE THREAD

**Issue by Skarletto** [RMC-14/RMC-14#3222]
![image](https://github.com/user-attachments/assets/ccd5431e-0c24-4b56-bde6-2c7b3878398e)

Why have one bag when you can have a morbillion bags

**Comment by B1essedknight** [comment]
dupe im pretty sure #3118

**Comment by Skarletto** [comment]
> dupe im pretty sure https://github.com/RMC-14/RMC-14/issues/3118

You're right
