### ISSUE TITLE
Charging crusher should push allies on the way aside instead of stopping after colliding with them.

### ISSUE THREAD

**Issue by Glek3197** [RMC-14/RMC-14#3235]
Right now charging crusher stops if encounters xenos or marines, but in cm13 crusher pushes allies aside, according to https://discord.com/channels/1168210010233376858/1261238058096001156/1265217338098061383, https://discord.com/channels/1168210010233376858/1261238058096001156/1265218350552973395, crusher pushes allies aside.
We should have crusher push allies aside in rmc14 too.
As of now it is really annoying to stop your offensive or (especially) escaping charge and die because lesser got in the way.

**Comment by Vermidia** [comment]
That would be for the Charger strain of Crusher, which is different.
