### ISSUE TITLE
Shotgun delay doesnt show

### ISSUE THREAD

**Issue by Verification31** [RMC-14/RMC-14#3278]
After you shoot a shotgun, the little wheel that shoes delay between shots wont show up. The popup that says you have to wait doesnt show either.

**Comment by Siigiil** [comment]
ShootUseDelayComponent is scuffed and I removed it from the guns that used it and replaced it with fire rate, planning to fix it  so it properly interacted with that instead of being a separate thing. Then promptly forgot about that plan. I'll fix this later.
