### ISSUE TITLE
Depending on where it lands it is possible for the ship to trap xenos during hyjack

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#3323]
## Description
Title

**Reproduction**
Be in the wrong place at the wrong time during hyjack 

**Screenshots**
![image](https://github.com/user-attachments/assets/8637af2a-63c7-4847-b1b4-3cd689ae4b12)

**Additional context**
making marine weapon racks breakable would fix this

**Comment by DrSmugleaf** [comment]
This should be fixed now with https://github.com/RMC-14/RMC-14/pull/3574
