### ISSUE TITLE
There is zero reason to take the marksman rifle over the M54C

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#3335]
## Description
This is the marksman rifle with ideal attachments:
![image](https://github.com/user-attachments/assets/6de2960f-66c9-47e0-a607-07d6330d5c99)

This is the M54C with ideal attachments:
![image](https://github.com/user-attachments/assets/3a080cba-c99d-42ec-8a2f-62307e3c8029)

The only advantage a marksman rifle has is the potential to use a smart scope, which is not a massive advantage when played correctly.

**Comment by DrSmugleaf** [comment]
This will be fixed by https://github.com/RMC-14/RMC-14/pull/3422 which ports damage fall-off, with the M4SPR having none

**Comment by deltanedas** [comment]
ap m4 on top

**Comment by DrSmugleaf** [comment]
Fixed in https://github.com/RMC-14/RMC-14/pull/3422
