### ISSUE TITLE
Indestructible railings

### ISSUE THREAD

**Issue by diraven** [RMC-14/RMC-14#3351]
## Description
These seem to be indestructible and impossible to acidify by xenonids.

**Screenshots**
![image](https://github.com/user-attachments/assets/143358a9-dbd2-460f-b382-c393289e5baf)

**Comment by Siigiil** [comment]
These aren't railings. They're platforms. It's how we fake having elevation. Not supposed to be destructible.

**Comment by diraven** [comment]
> These aren't railings. They're platforms. It's how we fake having elevation. Not supposed to be destructible.

You cant go though them though, but can shoot through them. Is that intentional? They create a very unintuitive situation where you got a random something  you can see through, can shoot though, but can't go through.

**Comment by Siigiil** [comment]
> You cant go though them though, but can shoot through them. Is that intentional? They create a very unintuitive situation where you got a random something you can see through, can shoot though, but can't go through.

It is. Though on CM, vaulting them is extremely quick and you start the doafter automatically if you walk into one.
![thing2](https://github.com/user-attachments/assets/89cda01e-39b6-4fae-8bd4-63142d0bbd32)

**Comment by diraven** [comment]
> > You cant go though them though, but can shoot through them. Is that intentional? They create a very unintuitive situation where you got a random something you can see through, can shoot though, but can't go through.
> 
> It is. Though on CM, vaulting them is extremely quick and you start the doafter automatically if you walk into one. ![thing2](https://private-user-images.githubusercontent.com/84070966/352707907-89cda01e-39b6-4fae-8bd4-63142d0bbd32.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNzI4NjcsIm5iZiI6MTcyMjA3MjU2NywicGF0aCI6Ii84NDA3MDk2Ni8zNTI3MDc5MDctODljZGEwMWUtMzliNi00ZmFlLThiZDQtNjMxNDJkMGJiZDMyLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDA5MjkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZmNlZjdjMzRjNmY3NGZmMmEwYWU4MjdiMzg2MjY0ZmIwNTIwMGZhY2I4ZjYzNTE1YTk4ZWI1Y2E5NmU2YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0ZKBxwoL5Ylg6E-2l9PNgrf2yRAzruFg4ABm_icfHsA)

I see. With that in mind it all makes sense.
