### ISSUE TITLE
Xenonids are able to see marine roles

### ISSUE THREAD

**Issue by Kaga-404** [RMC-14/RMC-14#3358]
## Description

Xenonids are able to see what role a marine is by shift-leftclicking them. It appears as "Character (Role)"

**Reproduction**

Shift-leftclick a marine while controlling a xenonid, and their role will be next to their name.

**Screenshots**

**Additional context**

**Comment by ARMOKS** [comment]
This feels intended

**Comment by FungiFellow** [comment]
Bugs reading dogtags

**Comment by deltanedas** [comment]
even if you remove it its trivial to just look at them and know that host with a smart spitter is smart spitter, host healing is druid etc

**Comment by Timemaster99** [comment]
On CM13, some will intentionally hide their medical markings or Comtech gear to obfuscate their role from xenos. For parity and for gameplay, this is a bug

**Comment by DummeHytteOst** [comment]
fixed by #5004
