### ISSUE TITLE
RMC-14 - The free night vision for marines update

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#3361]
## Description
Possible to abuse the way smart gun goggles work to get free night vision and extended vision as marine

**Reproduction**
Equip SG harness, Equip SG, Equip SG headmount, remove harness, profit.

**Screenshots**
The goddamn video is too big to upload and I cannot compress it rn, reach out to me on the discord and I can stream it to you.

**Comment by DrSmugleaf** [comment]
Would need to fix this by making the goggles drop if your smart gun is dropped, though I think originally I didn't because in 13 it doesn't either, since dropping your smart gun also dropping your goggles would probably get annoying.
This only works for as long as the goggles stay on, right? Like at most you can give someone else the goggles, then keep the rest of the kit yourself, and only 1 person has night vision?

**Comment by Dutch-VanDerLinde** [comment]
> Would need to fix this by making the goggles drop if your smart gun is dropped, though I think originally I didn't because in 13 it doesn't either, since dropping your smart gun also dropping your goggles would probably get annoying. This only works for as long as the goggles stay on, right? Like at most you can give someone else the goggles, then keep the rest of the kit yourself, and only 1 person has night vision?

yes

**Comment by ARMOKS** [comment]
> Would need to fix this by making the goggles drop if your smart gun is dropped, though I think originally I didn't because in 13 it doesn't either, since dropping your smart gun also dropping your goggles would probably get annoying. This only works for as long as the goggles stay on, right? Like at most you can give someone else the goggles, then keep the rest of the kit yourself, and only 1 person has night vision?

Yes, You could probably tie the goggles to the harness rather than the gun, as wearing the harness without the gun itself is a pretty massive disadvantage.

**Comment by ARMOKS** [comment]
Intended

**Comment by DrSmugleaf** [comment]
Talked about this in an ahelp in-game, but it's probably better to keep this behaviour as intended, otherwise if you get your armor taken off for a defib or surgery as a smart gun operator you're going to be in hell requipping all your stuff assuming it didn't get stolen in the mean-time
