### ISSUE TITLE
larva should gestate faster when in nest

### ISSUE THREAD

**Issue by deltanedas** [RMC-14/RMC-14#3378]
## Description
cm13 parity

would need a rework from AttachedAt/BurstAt to be an accumulator that increases with time + being nested + visible nested marines

**Comment by Vermidia** [comment]
It was removed in CM-13

**Comment by deltanedas** [comment]
from code diving multipliers for growth are:
- 0.33 if the host is in stasis or very cold and under stage 5
- 0.11 if the host is in stasis or very cold and at stage 4
- 1.5 if the host is nested
- 1 otherwise

**Comment by Vermidia** [comment]
Already does grow faster nested
