### ISSUE TITLE
Deconstructing barricades should yield less materials

### ISSUE THREAD

**Issue by Skarletto** [RMC-14/RMC-14#3449]
Deconstructing a barricade that was not damaged should yield 4 metal (_They currently all do_)

Deconstructing a barricade that only took a hit or two should yield 3 metal

Deconstructing a barricade that has visually taken damage should yield 2 metal

Deconstructing a barricade that is unrepairable (last damage stage) should not yield any metal

Deconstructing any barricade that has barbed wires on it should drop the barbed wires

https://github.com/user-attachments/assets/cf7af5ec-a539-43ee-bcef-92ddcd082546

**Comment by deltanedas** [comment]
> Deconstructing any barricade that has barbed wires on it should drop the barbed wires

you can use wirecutters to remove it before deconstructing not sure if its a required step in the graph or just optional

**Comment by Skarletto** [comment]
It should be optional, just deconstructing the barricade with your crowbar without taking off the barbs should just drop the barbs
