### ISSUE TITLE
You can sell the stamped papers in req rather than placing them on the boxes.

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#3454]
Steps:
Get 5 stamped papers.
put them all inside a single box.
Sell said box for 1500$
4 free boxes

**Comment by DangerRevolution** [comment]
This is how you do it in CM13?

**Comment by DangerRevolution** [comment]
You don't even need a box in CM13 (I think)

**Comment by deltanedas** [comment]
if you dont sell the boxes you get $200

being able to sell invoices isnt a bug, but the box $200 bit should be properly communicated instead of noobs being trolled
