### ISSUE TITLE
Weird parasite voodoo

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#3462]
Trying to figure out how to replicate, some dead parasite turned into this creature
![image](https://github.com/user-attachments/assets/4332d354-0f32-4cdd-9576-1ca90e7bc3af)

**Comment by ARMOKS** [comment]
It stops bullets too

**Comment by Vermidia** [comment]
It's dead, its the infection sprite

**Comment by Dutch-VanDerLinde** [comment]
> It's dead, its the infection sprite (though I messed it up the it is not moving part)

[italic]

**Comment by Dutch-VanDerLinde** [comment]
> It's dead, its the infection sprite (though I messed it up the it is not moving part)

this issue was that dead parasites from infection become a barricade as they eat bullets

**Comment by Vermidia** [comment]
Huh, all I did was change the sprite and text so that would be from before I changed anything I think.

**Comment by Dutch-VanDerLinde** [comment]
hard to reproduce, sometimes it acts as a barricade, sometimes it doesnt?

**Comment by ARMOKS** [comment]
> Huh, all I did was change the sprite and text so that would be from before I changed anything I think.

Please reopen this, there is a typo in the parasite description and they act like a barricade sometimes

**Comment by Vermidia** [comment]
Typo is fixed, I can rename it for the barricade problem

**Comment by DrSmugleaf** [comment]
Does this still happen after the change to targeting dead mobs?

**Comment by Dutch-VanDerLinde** [comment]
> Does this still happen after the change to targeting dead mobs?

No
