### ISSUE TITLE
Resin Building Animation for Lesser Drones is too fast

### ISSUE THREAD

**Issue by Rainbeon** [RMC-14/RMC-14#3472]
## Description
The new animation that plays with Resin Building does not currently account for the Lesser Drone's slower building speed, causing the animation to play and then disappear before completion of the structure

**Reproduction**
1) Build anything as a Lesser Drone
2) Structure will disappear ~60% of the way through, and then reappear on completion

**Comment by Dutch-VanDerLinde** [comment]
i can fix this, problem is that lesser drone's use the same animation as normal drones, will be fixed once xeno construction uses their own prototypes

**Comment by Tunguso4ka** [comment]
I leave there similar issue from the [Discord](https://discord.com/channels/1168210010233376858/1269080650795712573).
