### ISSUE TITLE
M83 and M79 grenades shoots through closed doors/shutters/podlocks

### ISSUE THREAD

**Issue by Tunguso4ka** [RMC-14/RMC-14#3480]
## Description

Title.
Both M83 and M79 grenade launchers is affected.
Throwing grenades by hand and by U1 grenade launcher (underbarell launcher) respects collision.

[Connected Discord Issue](https://discord.com/channels/1168210010233376858/1268282406205395107)

**Reproduction**

**Screenshots**

https://github.com/user-attachments/assets/65509714-7026-4168-a068-077d4ad91a1f

https://github.com/user-attachments/assets/376d2c92-eee1-4353-aba3-42405660781d

https://github.com/user-attachments/assets/424ca096-2b67-4576-9608-d663481f0070

**Comment by Dutch-VanDerLinde** [comment]
why does this even happen

**Comment by Dutch-VanDerLinde** [comment]
does this also apply to m79 grenade launcher and underbarrel or just the wep specialist one

**Comment by Tunguso4ka** [comment]
> does this also apply to m79 grenade launcher and underbarrel or just the wep specialist one

underbarrel no.
gonna test m79.

**Comment by Dutch-VanDerLinde** [comment]
does the underbarrel throw the grenade slower/further? does it have something to do with projectile speed

**Comment by Tunguso4ka** [comment]
> does the underbarrel throw the grenade slower/further? does it have something to do with projectile speed

updated issue with M79 GL and U1 GL video.

**Comment by Tunguso4ka** [comment]
> does the underbarrel throw the grenade slower/further? does it have something to do with projectile speed

underbarrel GL
```
projectileSpeed: 20
```
line 327 in `Resources/Prototypes/_RMC14/Entities/Objects/Weapons/Guns/Attachments/under_attachments.yml`

handheld GLs
```
projectileSpeed: 20
```
line 9 in `Resources/Prototypes/_RMC14/Entities/Objects/Weapons/Guns/Launchers/marine_launchers.yml`

**Comment by Tunguso4ka** [comment]
underbarrel GLs have maxFixedRange
```
  - type: ShootAtFixedPoint
    maxFixedRange: 7
```

**Comment by UnicornOnLSD** [comment]
do NOT let them know about this

**Comment by Dutch-VanDerLinde** [comment]
and is it specifically resin doors or thick doors/ normal metal doors

**Comment by Tunguso4ka** [comment]
> and is it specifically resin doors or thick doors/ normal metal doors

all doors: resin, thick resin, metal doors, airlocks, external airlocks, shutters, podlocks.
