### ISSUE TITLE
CMP headset is weird

### ISSUE THREAD

**Issue by dffdff2423** [RMC-14/RMC-14#3484]
## Description

The CMP headset does not have access to squad radio but the normal MP headset does? The CMP radio also has req access for some reason?

**Comment by Vermidia** [comment]
You are correct, they are supposed to have the squad radios but by default should be toggle off (we need toggling radio frequencies)
![image](https://github.com/user-attachments/assets/655e6791-bf38-48db-b3b8-28080bf22d43)

**Comment by dffdff2423** [comment]
In that case is it also supposed to be there for normal MPs? I don't really understand why MPs need req anyways.

**Comment by Vermidia** [comment]
It's not in normal MP (req)

**Comment by dffdff2423** [comment]
closing because the above PR was merged and should fix this.
