### ISSUE TITLE
There is no way to search webbing without removing somebodies jumpsuit.

### ISSUE THREAD

**Issue by dffdff2423** [RMC-14/RMC-14#3485]
## Description

There should probably be some way for MPs to search webbing without taking people's clothes off.

**Comment by Vermidia** [comment]
There is an action to remove "accessories" (aka webbing) from clothes in CM-13

**Comment by Siigiil** [comment]
I'll implement this when I move webbings onto the attachment system.

**Comment by Dutch-VanDerLinde** [comment]
Fixed , verb in strip menu now
