### ISSUE TITLE
Marines should appear in full gear (uniform, armor, helmet) in the character editor

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#3505]
CM13 parity

**Comment by Verification31** [comment]
something about this with xenos too? Your character just shows as naked when you high prio xeno.

**Comment by Dutch-VanDerLinde** [comment]
> something about this with xenos too? Your character just shows as naked when you high prio xeno. 

upstream pr that will make this possible if it's merged
