### ISSUE TITLE
Xenos are able to drag corpses to walls to put them on despite said corpse not being alive anymore

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#3512]
Title - Drag the corpse sprite to a wall

**Comment by Guess-My-Name** [comment]
i will just add, when someone's fixing this, make exception for dead people that were infected by a parasite
unless it's not an exception in cm13

**Comment by DaFieFie** [comment]
Nested bodies progress the larva state faster, thus nids should be able to nest dead infected marines, but not uninfected.
