### ISSUE TITLE
RMC - The baby melting update

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#3513]
WHY CAN THIS HAPPEN AHHH
![image](https://github.com/user-attachments/assets/83da326d-7bd1-4c56-a2e4-e999613d6c67)
1000 XENO ACID MELTED BABIES

**Comment by ARMOKS** [comment]
It works on closed eggs as well

**Comment by mmails** [comment]
you could have named this issue 100 other things
