### ISSUE TITLE
crusher charge still makes you go through barricades

### ISSUE THREAD

**Issue by Juan0045** [RMC-14/RMC-14#3527]
## Description
Crusher can still charge straight through barriers, getting stuck behind it and causing general chaos, it happens from the outer side of barricades aswell as the side, from the side you only go through 1 cade then you get stopped, this includes cades with barbed wire.

**Reproduction**
-be crusher
-find cade line
-charge directly at it from anywhere the cade touches the tiles edge
-end up stuck behind the cade without any way to get out

**Screenshots**

**Additional context**
i think whats happening is you get stopped on the tile the cade is on instead of right before it, im not sure if the cade even properly takes damage

I only tested this in one round yesterday and i was able to reproduce it 100% of the time i tried with cades that were abandoned, first time i did it had no idea this bug existed and charged into a cadeline with 10 marines to damage it, and caused that entire cadeline to fall as a result of the chaos that ensued from me suddenly popping up next to them

**Comment by DrSmugleaf** [comment]
This is to do with the physics update time, we often have to turn down the tick rate when it gets laggy

**Comment by Coolsurf6** [comment]
Got two recordings of this happening. This is a pretty active issue that is happening quite recently. I made a bug report for some people on discord who don't use Discord to document this as well. 

Here are two active recordings of this happening. The only way to deal with this is to have some level of math that checks in a previous tick right before impact, what side the crusher was on. If the tickrate is so low and causes the crusher to be so far on the other side, that they pop up on the other side, some math needs to happen to predict this, and always place the crusher on the side they charged from. 

My head thinks Super Mario 64 sub-tick collision. I have brainrot (but something like that, as funny as it is to mention)


https://github.com/user-attachments/assets/caefb11c-6aaa-4167-b211-9c5284a91052

https://github.com/user-attachments/assets/299fcfbf-2db0-474e-a041-40e62fed7777

**Comment by Dutch-VanDerLinde** [comment]
Fixed from new server pretty sure

**Comment by Juan0045** [comment]
> Fixed from new server pretty sure

Yup havent experienced this yet again, gonna close thanks for the reminder <3
