### ISSUE TITLE
empty bloodpack chem storage meta

### ISSUE THREAD

**Issue by deltanedas** [RMC-14/RMC-14#3549]
## Description
- they store 300u of any chem you want in the same space as a bottle
- you can directly refill your hypospray from them, **within your belt**
- if you try to use them in an iv it doesnt even work so idk

**Comment by Vermidia** [comment]
This is because our hyposprays can draw from containers which...they aren't supposed to.

Remaking hyposprays to work like they do in cm-13 would be a bit of work so I'll just disable container draw for hypos.

**Comment by Dutch-VanDerLinde** [comment]
> This is because our hyposprays can draw from containers which...they aren't supposed to.
> 
> Remaking hyposprays to work like they do in cm-13 would be a bit of work so I'll just disable container draw for hypos.

how they work in cm13

**Comment by Vermidia** [comment]
Ok, so hyposprays don't draw from containers at all, you can fill them with a bottle or you take take out their vial which is where they actually store the liquid (it's a 30u open container). You can only inject them into people.

**Comment by Dutch-VanDerLinde** [comment]
> Ok, so hyposprays don't draw from containers at all, you can fill them with a bottle or you take take out their vial which is where they actually store the liquid (it's a 30u open container). You can only inject them into people.

so like an item slot that fits a bottle?

**Comment by Vermidia** [comment]
Pretty much yeah. I think code wise it's treated like a gun magazine there.

**Comment by deltanedas** [comment]
how i think it could
- ItemSlots with a vial slot, whitelisted to the 30u vial
- CMHyposprayComponent that has the slot name
- CMHypospraySystem that gets the slot's vial and then gets its solution, injects an amount (idk if it can be changed from 5u in cm13 but if it can add a verb) into the target

**Comment by Dutch-VanDerLinde** [comment]
> how i think it could be implemented
> 
> * ItemSlots with a vial slot, whitelisted to the 30u vial
> * CMHyposprayComponent that has the slot name
> * CMHypospraySystem that gets the slot's vial and then gets its solution, injects an amount (idk if it can be changed from 5u in cm13 but if it can add a verb) into the target

yes the inject amount can be changed in cm13
just tested, works the exact same as a hypospray here but you cant draw from containers and the vial is detachable
you dont need to remove the vial to insert reagents

**Comment by Vermidia** [comment]
Btw, normal autoinjectors don't container draw either. So both of them should need to be filled directly by bottle.

**Comment by Vermidia** [comment]
Made a PR upstream to add disabling containerDraw to mob-only injectors. Once that's merged I'll merge the fix here.

**Comment by Vermidia** [comment]
Fixed by #3669
