### ISSUE TITLE
Pocket-sized Guns

### ISSUE THREAD

**Issue by Kezu02** [RMC-14/RMC-14#3550]
## Description

A player reported that their M63 and M4SPR could fit in their pocket. Other weapons in the area are unaffected, but the ones they were using somehow had the ItemSizeChange comp that probably shrunk it. No idea how it showed up.

**Screenshots**
![image](https://github.com/user-attachments/assets/c0447398-2255-4624-ad35-5dd6dee6b6fb)

**Comment by Siigiil** [comment]
It shows up when guns have size-changing attachments. The bug is because *somehow* the base size is not being set properly. I'm pretty sure I fixed this, but now it's popped up again. I'll try to figure out what's causing this shit.

**Comment by DaFieFie** [comment]
It's definitely attachments related. Still happening.

**Comment by Dutch-VanDerLinde** [comment]
Fixed
