### ISSUE TITLE
Almany Intercoms have all Comms Channels

### ISSUE THREAD

**Issue by Mojomuster** [RMC-14/RMC-14#3554]
## Description
The intercoms on the Almany have access to all communication channels

**Reproduction**
> Go to any intercom on the almany
>Berate High command on their own comms for the gross security issue

**Screenshots**
![image_2024-08-05_170642214](https://github.com/user-attachments/assets/a3af6b52-29fa-4f37-b105-df6697344513)

**Comment by Tunguso4ka** [comment]
Almany is Almayer.

**Comment by Tunguso4ka** [comment]
also, duplicate of #3171
