### ISSUE TITLE
Savannah Prep Room-Hijack Landing Point almost unusable

### ISSUE THREAD

**Issue by Rainbeon** [RMC-14/RMC-14#3587]
## Description
Since the new prep room introduced in #3456, the Prep Room Hijack drop point is almost unusable, forcing Xenos into only using one entrance and exit as the other two on the sides get blocked off by several sets of walls and doors, alongside this, many indestructible equipment racks fill the interior of the ship. 

For the Marines, it makes it impossible to enter the ship except through southern maintenance tunnels.

Also of note, the natural layout of the prep rooms in relation to the ship would naturally entirely block off the bottom exit as well, but for some reason in the round, a single wall despawned to allow exit. I am unsure if it does this every time, or if it has a chance to entirely block the ship off.
 
**Screenshots**
Charlie/Delta Hijack Point
![image](https://github.com/user-attachments/assets/fccabedf-b650-4631-92e3-e73f1de502d1)

Same image with (lucky?) despawns annotated by red X's
![image](https://github.com/user-attachments/assets/61c00519-4c27-4ca3-a49f-728ca550044b)

**Comment by Tunguso4ka** [comment]
oh...
