### ISSUE TITLE
smart pistol with laser loses accuracy when wielded

### ISSUE THREAD

**Issue by deltanedas** [RMC-14/RMC-14#3607]
## Description
without laser: 10 -> 10
with laser: 6 -> 8

**Comment by Dutch-VanDerLinde** [comment]
i think this is how the laser sight works, it reduces less accurary when its wielded

**Comment by deltanedas** [comment]
it actively makes it worse in this case meaning its better to hip fire

**Comment by Siigiil** [comment]
Not a bug. The laser sight has a stronger effect when the weapon isn't wielded.
