### ISSUE TITLE
Melee weapons needs to do 1.5x damage against xenos

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#3616]
## Description

**Reproduction**

It sure exists.
52.5 damage to a drone a machete does, so 1.5x it's normal damage.

Using it on yourself or other humanoids just does 35 damage (ignoring armor) but armor isn't ignored for xenos, since crusher takes less damage from it.

**Screenshots**

**Additional context**

**Comment by Vermidia** [comment]
I found where it's defined I think
[In here](https://github.com/cmss13-devs/cmss13/blob/04b313463e6645f7a68ffc62e7a8976a10cbc002/code/datums/combat_personalized.dm#L102)

**Comment by Vermidia** [comment]
Small addendum, throwing counts as melee

**Comment by Carolyn3114** [comment]
do they still not do this?

**Comment by Vermidia** [comment]
not yet
