### ISSUE TITLE
Armed M40 Grenades can be inserted into the U1 Grenade Launcher, functionally breaking the weapon

### ISSUE THREAD

**Issue by Rainbeon** [RMC-14/RMC-14#3643]
## Description
You can load an M40 HEDP that has been armed into the breech of the U1 grenade launcher, or any grenade launcher. If the grenade explodes while inside the breech, the ammo will not be subtracted, and that slot will never be refillable with a grenade ever again, effectively decreasing the amount of grenades it can carry. If the armed grenade that was loaded was the final one, the attachment/weapon will cease all function entirely.

**Reproduction**
1) Activate U1 grenade launcher attached to an M54C
2) Open the breech
3) Arm an M40 grenade
4) Insert the armed M40 grenade into the breech
5) Wait for the explosion
6) The bugged state is achieved

Works for all Grenade Launchers

**Screenshots**
Reproduction video
https://github.com/user-attachments/assets/bedb782d-81c3-4b26-b86e-0d27f45001ba

**Additional notes**
The explosion occurs on the attachment, so this can be abused to have "invisible" armed grenades (an average player is looking for a flashing grenade thrown at them, not an inconspicuous grey attachment that sort-of-looks-like-a-discarded-mag)

https://github.com/user-attachments/assets/ba94ff65-358b-487f-bfa1-18e6393eb573

**Comment by Dutch-VanDerLinde** [comment]
this is for every grenade launcher
