### ISSUE TITLE
SGs need to be capped at lowpop

### ISSUE THREAD

**Issue by deltanedas** [RMC-14/RMC-14#3647]
## Description
on lowpop you might have more SGs than riflemen, but xenos get barely any larva and just 1 queen
idk what cm13 does but this is really unfun, especially when all 4 power rangers combine in an ungaball with the sadars to demolish everything

**Comment by ARMOKS** [comment]
I disagree personally, lowpop favors xenos HUGELY and as soon as you get one good queen screech in you snowball, even if the marines ungaball.

**Comment by deltanedas** [comment]
screech is basically impossible to cap with since shaking was added, 1 guy with no armour uses a movespeed ability and instantly shakes the sgs and sadars awake, queen is instantly dead or at least stops dragging some marine

**Comment by MACMAN2003** [comment]
i have seen several people get capped with a screech, what are you talking about?

**Comment by Ariphylor** [comment]
> screech is basically impossible to cap with since shaking was added, 1 guy with no armour uses a movespeed ability and instantly shakes the sgs and sadars awake, queen is instantly dead or at least stops dragging some marine

This is such a niche comment. It's a specific scenario. This is implying that queen is screeching in a group full of people, a group so big, that there are people outside of the queens vision radius. This is also assuming that there's one guy there with movespeed buff who's job it is to shake people awake, who also didn't get caught in the scream.

Queen screech is fine as is. It's easy to capture with if you're good. If you're failing to cap with Scream, you're not using it correctly, or you got unlucky. Lowpop should remain unchanged. Keep in mind that on lowpop marines have almost no combat technicians or corpsmen. That should play in the Xenonids favor heavily.

**Comment by deltanedas** [comment]
i saw 5 rounds in a row a few days ago where my "niche comment" is what happened every round. ungaball gets screech sometimes with no flaw, marinw runner shakes the sgs instantly and no caps, a few xenos get killed too

**Comment by zerocool-0** [comment]
> ## Description
> on lowpop you might have more SGs than riflemen, but xenos get barely any larva and just 1 queen idk what cm13 does but this is really unfun, especially when all 4 power rangers combine in an ungaball with the sadars to demolish everything

skill issue

**Comment by Vermidia** [comment]
Fixed by #4094
