### ISSUE TITLE
cabinets are indestructible

### ISSUE THREAD

**Issue by lzk228** [RMC-14/RMC-14#3648]
these
![Screenshot_20240813_203242](https://github.com/user-attachments/assets/0d7d3d35-141a-45fb-ac8b-400f6015af3f)

**Comment by DummeHytteOst** [comment]
fixed by #5141

**Comment by DummeHytteOst** [comment]
also for clarification, it wasn't actually indestructible, it just had an insane dmg modifier, so anything with less than 30 brute dmg, would not be able to dmg it
