### ISSUE TITLE
Scout invisibility needs fixing

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#3691]
## Description

So scout is supposed to be this invisible:
![image](https://github.com/user-attachments/assets/ff364a06-479c-47b4-9151-a109ce4347ca)
but because of how it's handles its actually *very* visible
![image](https://github.com/user-attachments/assets/195f6fd7-b177-4884-9008-dc1f83cc0223)

**Reproduction**

**Screenshots**

**Additional context**

**Comment by LankLTE** [comment]
Note that it isn't just an issue of them being more visible than they should be, but specifically the skin color overwriting their equipped armor, which makes most colors contrast very poorly with black weeds.

**Comment by LankLTE** [comment]
This can be closed, it was changed to use a shader
