### ISSUE TITLE
Eggs are able to be planted in tiles with doors

### ISSUE THREAD

**Issue by vorkathbruh** [RMC-14/RMC-14#3696]
## Description

Xenonids are able to plant eggs in the mapped, metal doors, including the ones that are opaque which leads to a seemingly unintended egg trap. 

**Reproduction**

Spread weeds, open the door, plant egg in the door frame, close door.

**Screenshots**

**Additional context**

**Comment by zerocool-0** [comment]
I'm pretty sure it's a strategy that the Xenos can use as a way to place egg mines. it's not game-breaking just an easy way to build your Xeno army. if that's what you're talking about. advise looking before running into doors headfirst. and to have a group around you.

**Comment by deltanedas** [comment]
this is definitely a bug since recently it was made so you cant put eggmine in resin doors

**Comment by zerocool-0** [comment]
> this is definitely a bug since recently it was made so you cant put eggmine in resin doors

true I forgot about that

**Comment by vorkathbruh** [comment]
> I'm pretty sure it's a strategy that the Xenos can use as a way to place egg mines. it's not game-breaking just an easy way to build your Xeno army. if that's what you're talking about. advise looking before running into doors headfirst. and to have a group around you.

it would be a legitimate strat but they removed putting eggs in resin doors so i don't see why this is
