### ISSUE TITLE
Broken floodlights can be used as indestructible barricades

### ISSUE THREAD

**Issue by Carolyn3114** [RMC-14/RMC-14#3697]
## Description
Broken floodlights cannot be attacked nor destroyed while also being able to be unanchored.
This allows them to be used as indestructible walls that xenos can't get past, allowing marines to sit forever in corners or rooms.

**Screenshots**

https://github.com/user-attachments/assets/883645f4-51be-4fae-8530-a4f66732e5c9

check [this](https://discord.com/channels/1168210010233376858/1168210011823026274/1274421510324486348) discord message for a better video (it was too big)

**Comment by musicmanvr** [comment]
I love how I made sure to fix this and then it just didn't work 😀😀😀😀

**Comment by musicmanvr** [comment]
Them being indestructible is intended behavior though, they shouldn't be able to be unanchored

**Comment by UnicornOnLSD** [comment]
Popping this here quickly

CM parity, they're not moveable for a reason and generally can't be fully destroyed but have lengthy repair time
They were made impossible to move specifically for parity (and because people abused it)

**Comment by Dutch-VanDerLinde** [comment]
you cant unanchor flood lights anymore, so this is fixed i think
