### ISSUE TITLE
Xeno Damage On Lockers

### ISSUE THREAD

**Issue by Kezu02** [RMC-14/RMC-14#3707]
## Description

Xenos either deal no damage to or have no indicator when hitting lockers.

**Comment by Tunguso4ka** [comment]
Replicated on `029f0610bd`

Can damage: Queen, Ravager, Praetorian, Crusher, Warrior, Lurker.

Can't damage: Defender, Boiler, Spitter, Hivelord, Carrier, Burrower, Wehny, Sentinel, Runner, Rouny, Drone, Lesser Drone.

**Comment by Vermidia** [comment]
Might need to test in cm-13

The ones that can damage window frames in cm-13 match who can damage lockers here.

**Comment by Kezu02** [comment]
The ones on the ship give the red damage marker so it might be specific ones. It happened on Solaris. Was a locker blocking a door and idk how me and another xeno couldn't break it down.
