### ISSUE TITLE
Senior Officer Equipment Rack

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#3710]
CM13 has an equipment rack which changes based on what role you are

This rack is for the XO, CMO, CE, CMP, ASO, and QM

**Comment by DangerRevolution** [comment]
> CM13 has an equipment rack which changes based on what role you are
> 
> This rack is for the XO, CMO, CE, CMP, ASO, and QM

screenshot?

**Comment by Tunguso4ka** [comment]
> screenshot the contents

`code/game/machinery/vending/vendor_types/crew/senior_officers.dm`

![image](https://github.com/user-attachments/assets/1559e735-d62b-4ed3-bb6c-88985f04fa88)

**Comment by DangerRevolution** [comment]
> > screenshot the contents
> 
> `code/game/machinery/vending/vendor_types/crew/senior_officers.dm`
> 
> ![image](https://private-user-images.githubusercontent.com/71643624/358926143-1559e735-d62b-4ed3-bb6c-88985f04fa88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMDQxOTksIm5iZiI6MTcyNDAwMzg5OSwicGF0aCI6Ii83MTY0MzYyNC8zNTg5MjYxNDMtMTU1OWU3MzUtZDYyYi00ZWQzLWJiNmMtODg5ODVmMDRmYTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDE3NTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NTFmNzg2OGIxNGQ5OTcyZDgyNWM1NjE2MzI0ODlkMmYyOWNiNmNiZGExZDJiN2I4MjQzNTFlMjFiY2UyOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7I2vKHW8pJ1v_oIzYChZLfeQOWMT1AIFz0lO9p0aGtI)

This is ultimately a code request for dynamically changing vendors; not really sure if it merits an issue 🤷

**Comment by Aurallianz** [comment]
Ill work on this.
