### ISSUE TITLE
Matter dematerialization around stairs

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#3720]
## Description
Lack of item permanence around stairs, see screenshots for examples.

![image](https://github.com/user-attachments/assets/559b4f77-eaed-43eb-9404-179a830b4300)
![image](https://github.com/user-attachments/assets/84be6106-5af0-4041-a0b3-033cc932bb03)

**Comment by ARMOKS** [comment]
Items thrown also disappear, as well as characters that pass through the rift. They cannot be seen unless on the same floor

**Comment by DrSmugleaf** [comment]
Need z-projectors from 13

**Comment by DrSmugleaf** [comment]
Fixed by https://github.com/RMC-14/RMC-14/pull/3953
