### ISSUE TITLE
Stair grief V1

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#3723]
## Description
It is extremely easy to abuse how stairs work to create evil traps for executive officers and or invading xenos
**Reproduction**
create this but with reinforced walls
![image](https://github.com/user-attachments/assets/cfb86fea-7ee9-4ae3-b074-fb2a74bd7699)

**Comment by ARMOKS** [comment]
same can be done but even worse with ladders

**Comment by DrSmugleaf** [comment]
Fixed with https://github.com/RMC-14/RMC-14/pull/3815

**Comment by DrSmugleaf** [comment]
Still an issue with ladders

**Comment by DrSmugleaf** [comment]
Fixed for ladders in https://github.com/RMC-14/RMC-14/commit/947a24329db4f989b09058502ab193983b64b08c
