### ISSUE TITLE
RMC14 - The Great Escape

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#3729]
## Description
You can escape into space on the top floor of the marine ship with a breaching charge

**Reproduction**
us breaching charge on podlock

![image](https://github.com/user-attachments/assets/5c9e8970-9022-45f7-a874-8a2bc839fc4c)

**Comment by deltanedas** [comment]
umbilical is also meltable+boomable

**Comment by DrSmugleaf** [comment]
Fixed by replacing those with hull walls for now until we get the lifeboat doors
