### ISSUE TITLE
Slime people don't have underwear markings...

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#3734]
## Description

Title...

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Tunguso4ka** [comment]
![image](https://github.com/user-attachments/assets/1fe93806-bc45-4e1a-afa3-b3fa86039f8e)
they do?

**Comment by Tunguso4ka** [comment]
![image](https://github.com/user-attachments/assets/12f05955-44c9-49f1-bdfb-44a3e04a6160)
they do not...
