### ISSUE TITLE
Dropship navigation computers cannot be interacted with by the queen

### ISSUE THREAD

**Issue by DaFieFie** [RMC-14/RMC-14#3749]
Primary LZ or not does not matter.

**Comment by Vermidia** [comment]
I think sometimes command also can't pick primary lz? Not sure of this but it happened one round. Not sure if someone else picked it before I joined.

**Comment by Tunguso4ka** [comment]
Needs replicating.

**Comment by B1essedknight** [comment]
possibly already fixed? #3759

**Comment by Vermidia** [comment]
That likely was the problem
