### ISSUE TITLE
Smartgunner zoom levels return to default after binocular usage

### ISSUE THREAD

**Issue by DaFieFie** [RMC-14/RMC-14#3754]
You have to toggle it off and on again to fix it. Can you tell I use binoculars a lot?

**Comment by crystalHex** [comment]
There's also an issue where if you are scoped in (using binoculars or a scoped gun) and then toggle the smartgunner sight, you end up with the zoom of the latter, but the offset of the former (or in other words, your camera is unscoped and offset by an amount where you can't see yourself).
