### ISSUE TITLE
You can CAS fire on some parts of the western caves of solaris

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#3756]
## Description

Title. Happened in round # 837, it was one of the edges that allowed CAS.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Vermidia** [comment]
Going to assume this was fixed by the areas rework.

**Comment by DrSmugleaf** [comment]
Should be good now,  you can run areas:loadmortar to check
The very edge do allow mortar fire since it's considered close enough to the cave entrance
