### ISSUE TITLE
When very few xenos remain, ARES can give inaccurate results

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#3764]
![image](https://github.com/user-attachments/assets/2862a20f-479e-496e-b149-6e2bcc24e331)

Round 845

**Comment by GoodWheatley** [comment]
Intentional, the number the bioscan gives is almost never completely accurate to how many xenos are left. At low xeno numbers this happens in 13 too.

**Comment by Tunguso4ka** [comment]
ah, well, intended.

**Comment by ARMOKS** [comment]
> ah, well, intended.

I think this should be reconsidered. As a marine, if one sees that there are zero xenos left, the natural thing to do as well as RP thing to do would be to leave the planet.
