### ISSUE TITLE
Jones sometimes suffocates forever. 

### ISSUE THREAD

**Issue by DaFieFie** [RMC-14/RMC-14#3781]
Round 853 is where I saw this. The logs have not been elucidating. A rejuv did not fix them, and this probably is an issue with simple mobs in general. 

From what I can tell Jones started suffocating and, although the logs say he stopped, he kept taking suffocation damage even after being healed several times by marines.

**Comment by Tunguso4ka** [comment]
yeah, thats because Jones breathes...
