### ISSUE TITLE
Marines are always able to see job icons no matter what

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#3796]
In CM13 this functionality only happens when you're wearing a marine headset

**Comment by Vermidia** [comment]
It's specifically the squad visor that does this actually I think. Without it on you can't see icons.

**Comment by Dutch-VanDerLinde** [comment]
> It's specifically the squad visor that does this actually I think. Without it on you can't see icons.

no it's the headset

**Comment by Vermidia** [comment]
Yeah your right, it's the headset. The visor can only be deployed if you lose a headset/never had on looks like.
