### ISSUE TITLE
Dead Xenos Block Bullets

### ISSUE THREAD

**Issue by Kezu02** [RMC-14/RMC-14#3826]
## Description

A spitter and drone body somehow turned into improvised walls for xenos to escape.

**Comment by Dutch-VanDerLinde** [comment]
this is fixed latest update, can't reproduce

**Comment by Dutch-VanDerLinde** [comment]
this happens randomly, sometimes xeno corpses block bullets, sometimes they dont, no idea why it happens

**Comment by Dutch-VanDerLinde** [comment]
on a live game

**Comment by Dutch-VanDerLinde** [comment]
was kinda like the weird parasite bug #3462

**Comment by DrSmugleaf** [comment]
Fixed in https://github.com/RMC-14/RMC-14/commit/ed0f4a9959343ca981985563265e1500fee5db59
