### ISSUE TITLE
Examine Description Shows Contraband

### ISSUE THREAD

**Issue by Kezu02** [RMC-14/RMC-14#3829]
## Description

Syndies confirmed in RMC.

![image](https://github.com/user-attachments/assets/54a57590-2c50-4534-9be4-0e0bc0ce5c37)

**Comment by deltanedas** [comment]
theres a game cvar that can be set to false in the server cfg preset

**Comment by DrSmugleaf** [comment]
Forgot to say but it's fixed now in the live server, will push a commit to fix it on the repo too
