### ISSUE TITLE
Crit Larva don't recover on weeds or with recovery phermones

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#3853]
## Description

Title. You can prolong their life with warding but they will never heal back up.

They do in cm hence bug.

**Reproduction**

Punch larva. Watch as it bleeds out on weeds in your arms with your recovery pheromones not reaching it.

**Screenshots**

**Additional context**

**Comment by B1essedknight** [comment]
Does it matter on the quality of pheromones emitted or regardless are they just dying?

**Comment by Vermidia** [comment]
Pretty sure they die even with queen pheromones active. I've seen warding keep them from dying for minutes, but no type of recovery pheromones heals them in crit, even if the damage was small (like from a punch)

**Comment by Vermidia** [comment]
Ok, so I think the issue is they heal so little because of their health pool that drains more over time due to their critical state, making it so they never recover even with queen recovery pheromones

**Comment by Vermidia** [comment]
They heal with pheros now so good enough I guess
