### ISSUE TITLE
Security cameras aboard the Savannah are unnamed.

### ISSUE THREAD

**Issue by troytroy400** [RMC-14/RMC-14#3862]
## Description
None of the security cameras aboard the Savannah are named. 

**Reproduction**
Check a "ship security cameras" console. 

**Screenshots**
![image](https://github.com/user-attachments/assets/f7333632-9940-43d7-837b-9f68aaf46d11)

**Additional context**
N/A

**Comment by Tunguso4ka** [comment]
Wha-
Last time i checked they had "{area_name} #{num}" names...

**Comment by DrSmugleaf** [comment]
I forgor to save areas in Savannah with the area rework
