### ISSUE TITLE
Undershirt Clips Through Scrubs

### ISSUE THREAD

**Issue by troytroy400** [RMC-14/RMC-14#3867]
## Description
When using a custom undershirt from the markings section of the customization, your undershirt will show through the sleeves of the medical scrubs. To my knowledge, this happens regardless of color.

**Reproduction**
Wear scrubs with an undershirt selected. 

**Screenshots**
![image](https://github.com/user-attachments/assets/88557907-6378-48cd-8b72-208a380738ba)
![image](https://github.com/user-attachments/assets/2df8f040-df76-4e56-9196-6b24f029d4b3)

**Additional context**
N/A

**Comment by Vermidia** [comment]
![parity](https://github.com/user-attachments/assets/93f03c8f-770c-4d04-8585-468e47a5e013)
This is parity if you use longer-sleeved undershirts, so not a bug. Scrubs just have short sleeves.

**Comment by troytroy400** [comment]
CM13 parity has the sleeves of the scrubs going down to about the elbow, as you can see in the images the undershirt cuts off the sleeves completely.

**Comment by Vermidia** [comment]
Still not a bug 
![image](https://github.com/user-attachments/assets/522cc2dd-cc0a-4a9b-acf2-28d25ab4379f)
We either how outdated or slightly different scrub sprites

**Comment by troytroy400** [comment]
Got it.
