### ISSUE TITLE
Marines can CPR/suture/surgery multiple marines at the same time

### ISSUE THREAD

**Issue by AJimmyU** [RMC-14/RMC-14#3902]
## Description

Single marine can perform CPR on any number of marines simultaneously, overlapping the action bars. Same with suturing, bandaging, surgery etc.

**Reproduction**

1. Perform simultaneous CPR on a pile of dead marines
2. Observe overlapping action bars.

**Screenshots**

**Additional context**

**Comment by Vermidia** [comment]
Surgery and sutures are cm parity so I assume everything else is too, except maybe cpr

**Comment by Vermidia** [comment]
Ok you can't suture two people at the same time in cm-13
