### ISSUE TITLE
Needs to be a different in areas for mortar placement vs mortar fire

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#3913]
## Description

Level 1 areas block you from placing a mortar in them. Level 2 blocks actual fire from happening on that location. Currently mortars can't fire in level 1 areas, which is just, wrong.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by DaFieFie** [comment]
First discovered this on Solaris. Unsure how many maps are affected, but it makes the mortar useless on Solaris.

**Comment by DrSmugleaf** [comment]
Fixed in https://github.com/RMC-14/RMC-14/commit/a50561cb54c5657d32a0c564c6648ab5d1338042
