### ISSUE TITLE
Dying of pure bloodloss makes you unrevivable

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#3949]
## Description

Title. Defib only heals asphyxiation damage on clear so bloodloss remains and keep them dead.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
epinephrine?

**Comment by Vermidia** [comment]
Doesn't heal asphyxiation or bloodloss. Neither does defibbing

**Comment by Vermidia** [comment]
Fixed by #4515
