### ISSUE TITLE
guns likely for both dropships go out of position/sync when rotating camera

### ISSUE THREAD

**Issue by timons2991** [RMC-14/RMC-14#3963]
So, effectively, this happens when you rotate your camera with sitting on a dropship with guns.

to replicate it, sit somewhere in a dropship, then press your rotate camera keybind

![Snímka obrazovky 2024-09-06 223852](https://github.com/user-attachments/assets/f1c7dfe2-9239-4a73-8a0b-6bc304bf7de7)

**Comment by TheDoctor1977** [comment]
this is a dupe of #3925

**Comment by Vermidia** [comment]
sure is

**Comment by timons2991** [comment]
> this is a dupe of #3925

yeah, did not see that, really just reported it on first sight
