### ISSUE TITLE
Double engineering doors all access on Almayer. 

### ISSUE THREAD

**Issue by troytroy400** [RMC-14/RMC-14#3973]
## Description
All of the double doors in engineering on the Almayer are all access and accessible without an ID. 

**Reproduction**
Attempt to open any double engineering door on the Almayer without an ID. 

**Screenshots**
![image](https://github.com/user-attachments/assets/f0bf08a3-9829-4911-938f-55f9f235a829)
![image](https://github.com/user-attachments/assets/158c6fb9-dde5-4d57-b89b-9c675a5a97ca)
![image](https://github.com/user-attachments/assets/cf1dc97d-2d5c-42ef-bc83-9b5852f41c35)

**Additional context**
N/A

- #2393

**Comment by Vermidia** [comment]
Dupe of #3737 (all doors are effected)
