### ISSUE TITLE
Bipod undeploying issue

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#3989]
Sometimes when you deploy your bipod and shoot in a direction, it'll undeploy even if you are shooting at the correct angle

However redeploying the bipod lets you shoot in the angle your aiming at?

**Comment by deltanedas** [comment]
90% sure this is real still

**Comment by Rainbeon** [comment]
It worked correctly for its defined behavior at the time but it is getting its own mechanics anyway so

**Comment by Dutch-VanDerLinde** [comment]
> 90% sure this is real still

I didn't understand on how bipod works at the time

Currently if you face and shoot in a different direction then you deployed the bipod at (your character changing directions), it undeploys
