### ISSUE TITLE
Xeno Night Vision can cause invisible Scout WS to be fully visible

### ISSUE THREAD

**Issue by Rainbeon** [RMC-14/RMC-14#4006]
## Description
Xeno Nightvision sometimes does not respect the Scout Weapon Specialist's Thermal Cloak invisibility and displays them as if they are completely 100% visible. This does not require the Xeno to take any unique actions for it to occur, it happens over the course of natural gameplay.

**Reproduction**
I can not currently find any way to manually reproduce this, but it occurs naturally over normal gameplay. May have something to do with latejoins?

**Screenshots**
https://github.com/user-attachments/assets/36464f35-950a-4cef-82d5-1f2ac110ee9f

Only extra context for this occurrence is that I had very recently joined the game, and very recently joined in as Xeno Larva (joined <10 minutes prior), unknown if circumstance is related.

**Comment by Dutch-VanDerLinde** [comment]
https://cdn.discordapp.com/attachments/1168210011823026274/1278022352948433031/yqQezSqUuv0jtgYuBfBy-w.mp4?ex=66e26851&is=66e116d1&hm=517a90c9cae103ea09b03214c6bb67ed1db20af218ed9b779f63e4e3b2f781f6&

More evidence

**Comment by Vermidia** [comment]
Should be fixed by #4016, if it persists after the next update I can reopen this
