### ISSUE TITLE
Structural damage boost doesn't work on masterkey

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#4008]
## Description

It actually takes more hits because only the normal damage modifer seems to be applied. It's 3 with normal pump vs 5 with masterkey. Might be similar to the IFF bug with shotguns.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Vermidia** [comment]
It does work on non-resin doors. Is it supposed to work on resin?

**Comment by Vermidia** [comment]
Nope the damage seems right, matches cm

**Comment by GoodWheatley** [comment]
> It does work on non-resin doors. Is it supposed to work on resin?

The masterkey breaks both regular and resin doors in one point-blank shot on 13.

**Comment by Vermidia** [comment]
It didn't seem to when I tested it. I was testing walls though in cm not doors.
