### ISSUE TITLE
RMCRepairable doesn't use or require fuel

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#4015]
## Description

Sentry healing is freeeeeeeeeeeeeeeeeee.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Dutch-VanDerLinde** [comment]
Why is RMC repairable a thing

**Comment by Vermidia** [comment]
because upstream welding code is sad

**Comment by DrSmugleaf** [comment]
> Why is RMC repairable a thing

First issue was that healing gets improperly split, specifying 20 Brute will not heal 20 Blunt if that's the only damage type on the entity
Then after that I found a few more thing with it that didn't fit our requirements and it took less time to just make a new system

**Comment by Vermidia** [comment]
Sentries actually are supposed to use 0 fuel - but still need the welder to be on and have fuel. Already in an upcoming PR so closing this rn,
