### ISSUE TITLE
Parasites can't leap onto nested hosts

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#4026]
If you throw them onto a nested host they will start the do-after, but when the do-after completes they will not infect the host?

**Comment by Vermidia** [comment]
They are trying to leap I think. Nested hosts don't count as down so they don't infect them. If they infect hosts on walls in cm, it's a bug. Otherwise, it's uh, parity I guess??

**Comment by Dutch-VanDerLinde** [comment]
even if its parity it should still be fixedb ecause you HAVE to get a drone to infect a nested host, and a player parasite is already able to infect nested hosts so why wouldnt the ai also be able  to do the same

**Comment by Vermidia** [comment]
Because that's a drones job? You're not supposed to be able to pull non-player ones technically. And not supposed to be able to pick up player ones.
