### ISSUE TITLE
Impact ammo doesn't apply a stun/knockdown

### ISSUE THREAD

**Issue by DummeHytteOst** [RMC-14/RMC-14#4045]
## Description
Shooting any xenonid with the scouts impact ammo will not apply a stun/knockdown, doubt it is even applying a slowdown.
the knockdown is purely visual in all my attempts at using it, allowing xenos to continue moving and attack

**Reproduction**
use impact ammo on a xenonid

https://github.com/user-attachments/assets/38735ace-bd68-4cd6-a40e-31cde0e89657

**Comment by TsjipTsjip** [comment]
In the video shown your client thought the shots were hits, but you did not hit a single shot in that clip according to the server. If you remember the round ID you can verify this on the replay.

I've played as a Xeno against a scout before past last update, their ammo is really nasty. I assure you, it works.

**Comment by DummeHytteOst** [comment]
> In the video shown your client thought the shots were hits, but you did not hit a single shot in that clip according to the server. If you remember the round ID you can verify this on the replay.
> 
> I've played as a Xeno against a scout before past last update, their ammo is really nasty. I assure you, it works.
> 
> EDIT (Original post maintained for posterity): It looks like you did hit a shot at the end of the clip. Note that the stun is incredibly short as-is right now. I'm told this might still be a bug, but the stun does apply correctly.

i did infact hit the runner both times it looked like it connected, i have now found out that the momentum apparently didn't get stopped, which made it look like they didn't get stunned, i believe #4023 has fixed this, the stun should probably be slightly longer imo, but i will be closing this issue 

https://github.com/user-attachments/assets/e8c8cecd-a192-4931-b3be-23537a6f0009
