### ISSUE TITLE
Xeno Free Slots

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#4093]
## Description

Hives have 3 free slots, 1 for a burrower, 1 for a carrier, and 1 for a hivelord, that don't count towards the t2 limit. We haven't ported this yet but prob should since we're getting the other support castes soonish

**Reproduction**

**Screenshots**

![image](https://github.com/user-attachments/assets/a0592132-671c-4365-8732-c4e05d40b5d8)

**Additional context**

**Comment by Dutch-VanDerLinde** [comment]
was this added

**Comment by Vermidia** [comment]
yeah for the most part. We're only missing burrower (which is being worked on I think) so I'll close it.
