### ISSUE TITLE
Non empty Revolvers eat Speedloader ammo

### ISSUE THREAD

**Issue by CrackedEmerald** [RMC-14/RMC-14#4103]
## Description
Reloading a revolver who's missing any number of bullets greater than zero with a Speedloader, erases the number of bullets that would be inserted.

**Reproduction**
Grab revolver 
Shoot
Use Speedloader on revolver
Revolver now has the same amount of bullets, and Speedloader has one less

**Additional context**
It always removes the number of missing shots im the revolver, if it's missing one two three four or even six, it'll remove that number of rounds from the Speedloader, and the revolver will not be reloaded.

**Comment by Rainbeon** [comment]
This is apparently a 2 year old upstream bug that has literally NEVER been reported until now thank you for making this issue, fix soon
