### ISSUE TITLE
Xenos should be able to flick/hit lights off

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#4132]
## Description

Title, specifically any lights including attachment ones. Parity. Some break on interact and can no longer turn back on,

**Reproduction**

**Screenshots**

https://github.com/user-attachments/assets/35161d32-1884-4ed7-87e8-94a45c72a0b3

**Additional context**

**Comment by B1essedknight** [comment]
Does this also include a way for Xenos to be able to "turn off" the lights on a holstered weapon, 
an example could be the smartgun with a rail light since that auto snaps to the harness.

**Comment by Vermidia** [comment]
No, but this is because holstered weapons don't emit light in cm-13.

**Comment by Vermidia** [comment]
Should be fixed by #5123
