### ISSUE TITLE
Queen being stuck on REQ pit

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [RMC-14/RMC-14#4134]
## Description
Under certain conditions the queen can become stuck on the REQ elevator causing certain death for the queen.

**Reproduction**
Position cades like picture below, and walk through as a queen

**Screenshots**
![image](https://github.com/user-attachments/assets/b7813384-6b6f-4229-9d5c-fd0cc5403fa5)

**Comment by Kadeo64** [comment]
@DrSmugleaf should this be closed?

(🐛 - Fixed the Queen getting stuck on some things like Req railings.)

**Comment by DrSmugleaf** [comment]
> @DrSmugleaf should this be closed?
> 
> (🐛 - Fixed the Queen getting stuck on some things like Req railings.)

ye ty
