### ISSUE TITLE
spitter/boiler spray acid blocks bullets

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#4148]
title

**Comment by MACMAN2003** [comment]
it's an optical illusion, your brain tricks you into thinking.

**Comment by Dutch-VanDerLinde** [comment]
> it's an optical illusion, your brain tricks you into thinking.

RMC schizophrenia update?

**Comment by DrSmugleaf** [comment]
Fixed already for next update but its a visual bug
