### ISSUE TITLE
Almayer Treatment Center Doors All Access.

### ISSUE THREAD

**Issue by troytroy400** [RMC-14/RMC-14#4153]
## Description
The treatment center doors on the Almayer are all access. For parity, really only medical staff, select command and corpsmen should have access.

**Reproduction**
Attempt to open treatment center doors with no ID.

**Screenshots**
![image](https://github.com/user-attachments/assets/220f64b9-0f41-4d93-a56a-494723018f84)

**Additional context**
N/A

- #2393

**Comment by TheDoctor1977** [comment]
I believe the doors to the east medbay entrance _are_ locked, so this is purely a mapping error.
