### ISSUE TITLE
you need to be able to instantly shoot a shotgun without delay but also not be able to dual wield

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#4169]
when you first equip a shotgun theres a 3 second delay, this is the swapping hands cooldown thing, but should only apply when you swap hands for shotguns and not on equip

**Comment by Vermidia** [comment]
https://github.com/cmss13-devs/cmss13/pull/4402 theres a thing called fire delay groups that prevents both guns from firing, only used on shotguns

**Comment by Dutch-VanDerLinde** [comment]
https://github.com/RMC-14/RMC-14/pull/4191
