### ISSUE TITLE
LV robotics button doesn't toggle the pod doors

### ISSUE THREAD

**Issue by DrSmugleaf** [RMC-14/RMC-14#4171]
On the left, next to LZ2

**Comment by Dutch-VanDerLinde** [comment]
I couldn't figure how to link the podlocks so i just gave up

**Comment by DrSmugleaf** [comment]
@Dutch-VanDerLinde 
VV edit the RMCPodDoor and RMCPodDoorButton components IDs, there's no UI for it rn
For the button you can do it manually, for doors run this while near them
`self nearby 3 with RMCPodDoor do "vvwrite /entity/$ID/RMCPodDoor/Id idtoset"`, changing idtoset

**Comment by DrSmugleaf** [comment]
Fixed in https://github.com/RMC-14/RMC-14/pull/4195
