### ISSUE TITLE
Praetorian Spray Acid applies Acid Stacks multiple times if target is not centered on a tile

### ISSUE THREAD

**Issue by Rainbeon** [RMC-14/RMC-14#4180]
## Description
Praetorian's Acid Spray normally applies 2 acid stacks, however if a marine is standing between two tiles, rather than the center, they get the 2 acid stacks applied + an additional 2 after that.

**Reproduction**
Video Reproduction
https://github.com/user-attachments/assets/71bff2e0-ed15-42c4-acfa-d08e5efb3d1f

**Comment by DrSmugleaf** [comment]
This is intended, in 13 if you walk away from the acid you can get hit multiple times, though it is true that if you are standing still between tiles you will get hit multiple times if the direction matches up
