### ISSUE TITLE
scouts need to uncloak if they're knocked down

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#4181]
mainly so marines can actually see dead scouts and also so xenos can see their captures

**Comment by Rainbeon** [comment]
Do they uncloak for stuff like Runner Pounce or Crusher Stomp? Since both do knockdowns as well

**Comment by Dutch-VanDerLinde** [comment]
> Do they uncloak for stuff like Runner Pounce or Crusher Stomp? Since both do knockdowns as well

if they go crit, die, stunned, i think check cm13 for confirmation though
