### ISSUE TITLE
praes can use all their abilities when resting

### ISSUE THREAD

**Issue by Kadeo64** [RMC-14/RMC-14#4182]
## Description
praetorians can use all their abilities (spit, ball, spray, corrode) while resting (except dash)

**Reproduction**
play normal (not warden) prae, try to spit while sleeping
**Screenshots**
i don't actually have a screen recorder
**Additional context**
i have not tested this with warden

**Comment by deltanedas** [comment]
warden can yoink xenos while resting too

**Comment by Vermidia** [comment]
Fixed by #4187
