### ISSUE TITLE
Shutters should be pryable by xenos

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#4196]
## Description

**Reproduction**

**Screenshots**

**Additional context**

**Comment by DrSmugleaf** [comment]
Which ones? The Almayer ones at least aren't pryable

**Comment by Dutch-VanDerLinde** [comment]
> Which ones? The Almayer ones at least aren't pryable in 13

solaris ones i think

**Comment by DrSmugleaf** [comment]
Those don't seem pryable either but I'll load solaris in 13 and test later
