### ISSUE TITLE
Epinephrine heal the wrong amount

### ISSUE THREAD

**Issue by GGlut** [RMC-14/RMC-14#4199]
**Description**
Epinephrine is supposed to heal 20 damage per type and not 5
Epinephrine has ELECTROGENETIC 4 and has a potency multiplier of 5 so it should heal 20.
Either i am missing something or the cm13 wiki (which says 16) is also wrong.

N/A

**Reproduction**
N/A

**Screenshots**
N/A

**Additional context**
CM Parity

**Comment by DrSmugleaf** [comment]
From 13 its electrogenetic 4 and multiplier 5 yes, normally it would be halved since potency is half the level but since epinephrine is triggered outside of the normal system it should be 20, I'll fix it

**Comment by deltanedas** [comment]
also from experience wiki is wrong compared to the actual code so dont 100% rely on it

**Comment by GGlut** [comment]
yeah i did plug the numbers out of the code because there wiki says normal defieb does 12+4 and and 12+16 with epi and i wanted to find out where the +4 comes from i still dont know where the wiki pulled that number from. Thats why i found its its 20 instead from the code.
