### ISSUE TITLE
resin hole code is in xeno announce system

### ISSUE THREAD

**Issue by deltanedas** [RMC-14/RMC-14#4224]
## Description
:warning: rushed code alert :warning:

**Comment by Vermidia** [comment]
I mean it's very easy to move, I just didn't bother? It was there in the first place due to resin hole not really having stuff set up for a shared system but now it does so it's pretty easy to move

**Comment by Vermidia** [comment]
I guess I'll move it since I touched it recently anyway

**Comment by deltanedas** [comment]
i trolled myself now i will have to fix conflicts :trollface:

**Comment by Vermidia** [comment]
Fixed by #4216
