### ISSUE TITLE
larvas inside hosts die in FTL

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#4255]
they "crash land to the planet" but they dont actually crash land since inside host

**Comment by Dutch-VanDerLinde** [comment]
![image](https://github.com/user-attachments/assets/34b0af32-bfac-49db-851c-5765645962cf)

**Comment by Vermidia** [comment]
They're already dead once you land too, this is pretty bad.

**Comment by Dutch-VanDerLinde** [comment]
how does this even hapen...

**Comment by Dutch-VanDerLinde** [comment]
So need to attach the larva and both parasites to the grid

**Comment by Dutch-VanDerLinde** [comment]
I have a branch which fixes this will PR soon
