### ISSUE TITLE
small light fixtures unpowered in almayer maints

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#4258]
![image](https://github.com/user-attachments/assets/1a14dbdf-0d9d-4019-bfd8-b6e10f7a9180)

**Comment by DrSmugleaf** [comment]
Are these still happening after the first round?

**Comment by Dutch-VanDerLinde** [comment]
> Are these still happening after the first round?

this was like the 3rd or 2nd round i think
