### ISSUE TITLE
Lights Have Limited Charge

### ISSUE THREAD

**Issue by troytroy400** [RMC-14/RMC-14#4262]
## Description
The hardhat and flashlight have limited power from upstream currently. CM parity is that they should not have a power limit. This is especially important for engineering who don't have another light source.

**Reproduction**
N/A

**Screenshots**
N/A

**Additional context**
CM Parity.

**Comment by Dutch-VanDerLinde** [comment]
the CM13 hardhat variants need to be ported too, they have the wrong sprite
