### ISSUE TITLE
Missing materials from engineering supply. 

### ISSUE THREAD

**Issue by troytroy400** [RMC-14/RMC-14#4265]
## Description
The CE emergency materials supply is missing a stack of plasteel.

**Reproduction**
N/A

**Screenshots**
![image](https://github.com/user-attachments/assets/6741ab5d-00bc-4f0c-85bd-c6d279aa3484)

**Additional context**
CM parity.

- #2393

**Comment by troytroy400** [comment]
I don't wanna open up a separate issue for it, but a glass stack is also missing from maints north of the ASOs office.
![image](https://github.com/user-attachments/assets/b3a882d9-c741-4fbc-b873-f27fe6057d03)

**Comment by DrSmugleaf** [comment]
Fixed next round
