### ISSUE TITLE
Item eggs can be shot to death

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#4296]
## Description

Title. I think in cm like most items you uh, can't do this? would have to check.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
you cant melee it so there would be no way to destroy it without asking a drone to plant it first

**Comment by Vermidia** [comment]
Counterpoint: Guns on marines. Carriers have been dropping eggs and they've just been shot to death. Not a problem now but RND in the future will be very sad.

https://github.com/user-attachments/assets/8b8b6814-67d5-48d9-b4f5-33c4b5ca2b22

This is what shooting items does in cm

**Comment by Kadeo64** [comment]
commenting to follow this issue

**Comment by deltanedas** [comment]
![02:30:51](https://github.com/user-attachments/assets/49bc3692-ee9b-465a-9cb4-1bef5caa0351)
:trollface:
