### ISSUE TITLE
SEA weapon rack provides no points.

### ISSUE THREAD

**Issue by troytroy400** [RMC-14/RMC-14#4309]
## Description
The SEA weapon rack give you no points, making it so that ammo is unobtainable.

**Reproduction**
Attempt to get a magazine from the SEA weapon rack.

**Screenshots**
![image](https://github.com/user-attachments/assets/bf34e96c-1ca9-4661-b043-6305731aed60)

**Additional context**
N/A

**Comment by DrSmugleaf** [comment]
Fixed next round
