### ISSUE TITLE
Squad room doors are not locked to the relevant squads.

### ISSUE THREAD

**Issue by troytroy400** [RMC-14/RMC-14#4310]
## Description
Squad room doors are not locked to the relevant squads (they're all access), in CM parity only the relevant squad can open their own doors.

**Reproduction**
Attempt to open any squad room double door without an ID.

**Screenshots**
N/A

**Additional context**
CM parity.
Relevant to - #2393

**Comment by Rainbeon** [comment]
Double doors in general do not currently function with access locking #3737

**Comment by Vermidia** [comment]
Closing as said it's a double door issue that's tracked in 3737
