### ISSUE TITLE
crit overlay doesnt appear anymore

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#4318]
1. go crit
2. no white overlayh

**Comment by MACMAN2003** [comment]
i can consistently get this to happen by leaving and rejoining without restarting the client

**Comment by TeaTotalTemplar** [comment]
> i can consistently get this to happen by leaving and rejoining without restarting the client
yep, same results on my end
start dev build
load in
damage self to crit, the vignette correctly applies
rejuvenate
disconnect
reconnect
repeat, no vignette

**Comment by Dutch-VanDerLinde** [comment]
Only appears on re connect if you crash and seems to be an upstream issue
