### ISSUE TITLE
Lurker Parity: Lurker Invisibility only ends when attacking a mob, not anything else

### ISSUE THREAD

**Issue by Rainbeon** [RMC-14/RMC-14#4353]
## Description
In CM13, Lurkers can attack as much as they want, as long as they don't hit a mob like a Marine. This means they can break windows, lights, cameras, or even Barricades without de-cloaking.

**Video**
https://github.com/user-attachments/assets/449894f8-a574-4a49-9713-bf1afa89f44b

**Comment by Dutch-VanDerLinde** [comment]
dupe issue

**Comment by Vermidia** [comment]
Ah yeah #4043 dupe
