### ISSUE TITLE
Strange APC

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#4393]
![image](https://github.com/user-attachments/assets/91ab71a9-1fbb-4a5b-861c-520dd2b0904b)

**Comment by Dutch-VanDerLinde** [comment]
![image](https://github.com/user-attachments/assets/60f4b6e4-27a4-42da-8842-818d60dc91a3)

**Comment by MACMAN2003** [comment]
that apc is from the parallel universe where the northern solaris caves are more open and have buildings in them

**Comment by Vermidia** [comment]
yep
A few people want it back by now so I wouldn't be opposed to putting it back, someone jsut needs to remap em in.

**Comment by DrSmugleaf** [comment]
I already remapped the old caves in in my survivor PR
