### ISSUE TITLE
Gardener can't plant fruit, even on its own planted weeds

### ISSUE THREAD

**Issue by crystalHex** [RMC-14/RMC-14#4473]
## Description

The gardener fails to plant fruit even on its own weeds

**Reproduction**

1. Be gardener
2. Plant weeds, either kind
3. Attempt to plant fruit
4. Be rejected by your own weeds
5. Sad

**Screenshots**

https://github.com/user-attachments/assets/b8a918ff-f939-47b4-9773-0e82b3121dbe

**Additional context**

**Comment by Vermidia** [comment]
This is because you're hiveless, so you don't count as the same hive. It works if you assign a hive.

**Comment by crystalHex** [comment]
damn, that's a skill issue on my part then
