### ISSUE TITLE
Runner/Lurker Parity: You can take actions while you are Leap self-stunned

### ISSUE THREAD

**Issue by Rainbeon** [RMC-14/RMC-14#4530]
## Description
The "stun" we have on Runner/Lurker leap hits are meant to be a Root, not a Stun. You can hit, shove, or start grabs while Rooted. You just can not move.

**Videos**
https://github.com/user-attachments/assets/213cc551-f6aa-4728-8c3d-a2ab45d08f5d

https://github.com/user-attachments/assets/b428f224-8439-4122-9a61-25f622970ac9

**Comment by Dutch-VanDerLinde** [comment]
would be ez to add, just add a movement modifier instead of stun
