### ISSUE TITLE
You should not be able to drag downed Marines through tables/window frames/etc

### ISSUE THREAD

**Issue by Rainbeon** [RMC-14/RMC-14#4531]
## Description
Marines and Xenos should not be able to be dragged through anything that only the Runner can uniquely pass through. This currently only seems to happen when they are laying down.

**CM13 Video**
https://github.com/user-attachments/assets/979b67c7-dfe9-46ba-97d9-c8df9f281aed

**Comment by DummeHytteOst** [comment]
fixed by #4660
