### ISSUE TITLE
cannot put motion detector in suit slot, and when in belt slot it does not work

### ISSUE THREAD

**Issue by Carolyn3114** [RMC-14/RMC-14#4541]
## Description

not parity
**Reproduction**

suffer
**Screenshots**

![image](https://github.com/user-attachments/assets/664e8684-2fc2-4218-b5fa-0aca8d20b38f)

**Additional context**

**Comment by Kadeo64** [comment]
bumping this to say that this is happening with all correspondent jackets although I don't know if that's parity with cm13.

**Comment by Ammoniacres** [comment]
I'll try to work on this, doesn't sound too hard and would be massive QOL.

**Comment by Dutch-VanDerLinde** [comment]
> I'll try to work on this, doesn't sound too hard and would be massive QOL.

there's already a pr for it

**Comment by Dutch-VanDerLinde** [comment]
fixed by #4537
