### ISSUE TITLE
Motion detectors work on dead, dragged xenos

### ISSUE THREAD

**Issue by Alekshhh** [RMC-14/RMC-14#4569]
yessir

**Comment by Kadeo64** [comment]
can confirm.

they also still work after the xeno has stopped being dragged for about 2-3 more pings on average before the motion detector cuts out again

**Comment by Kadeo64** [comment]
> This is parity, its intentional.

i mean I get why but it's also clunky

**Comment by Rainbeon** [comment]
Motion detectors detect movement, not life

**Comment by Alekshhh** [comment]
fair nuff
