### ISSUE TITLE
moth emotes have no sounds

### ISSUE THREAD

**Issue by deltanedas** [RMC-14/RMC-14#4581]
## Description
everything in the wheel (except scream), salutes, etc
1. use the squeak/buzz emote
2. nothing

**Comment by Vermidia** [comment]
This seems to work fine? Emote cooldown does some weird things but otherwise it works.

**Comment by deltanedas** [comment]
doesnt work unless im on permanent cooldown (and scream action seems to bypass it)

**Comment by Vermidia** [comment]
I really can't replicated this, lastest master and all. Tried using a male moth, female moth, etc. The emotes still work?

**Comment by deltanedas** [comment]
guid backdoor to prevent me specifically using emotes :trollface:
