### ISSUE TITLE
Command pouch doesn't allow a sidearm

### ISSUE THREAD

**Issue by mmails** [RMC-14/RMC-14#4588]
## Description

Command pouch descriptions claims it can hold a sidearm, yet to my DISMAY it does NOT hold a sidearm.

**Reproduction**

Attempt to holster a sidearm inside the pouch, be absolutely shocked and baffled when it doesn't allow you. Curl up on the floor and cry.

**Screenshots**
 N/A

**Additional context**
 N/A

**Comment by mmails** [comment]
Description also says it can hold binoculars and the command tablet, i forgot but it also doesn't allow one of those 2.

**Comment by Vermidia** [comment]
Issue is it's max size for items wasn't updated. Either it needs to be able to hold larger items or it needs the tablet and sidearm sizes to be ignored.

**Comment by DrSmugleaf** [comment]
Done in https://github.com/RMC-14/RMC-14/pull/4517
