### ISSUE TITLE
Gun melee doesn't have a gun melee cooldown for other guns

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#4633]
## Description

Title. Attacking melee with a gun should not allow you to immediately melee with a different gun in the other hand. Parity!

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Dutch-VanDerLinde** [comment]
yeah this is because if you have the melee cooldown it cooldowns the guns too for some reason? so only thing that needs to be done is to just make those two cooldowns independent
