### ISSUE TITLE
Potentially Missing Feature: Gardener Feeding Queen also feeds Observed Xeno

### ISSUE THREAD

**Issue by EpicJoston** [RMC-14/RMC-14#4653]
## Description
According to CM13 Wiki, description for the Gardener's Plant Fruit ability reads as such:

Plant a resin fruit on the ground beneath you.
Can be picked up and fed to other xenos by click dragging it to yourself. If you feed the Queen and she is observing a xeno, with both being on the same z-level then, the observed xeno and the queen both benefit from the fruit.

Potentially missing feature detected, wiki may be outdated.

**Comment by Vermidia** [comment]
Removed feature
