### ISSUE TITLE
Alamo got two phones stacked into one single place.

### ISSUE THREAD

**Issue by DasIrrlicht** [RMC-14/RMC-14#4679]
## Description
Alamo got two phones stacked into one single place, see title. This also means you can not click the ringing one reliably.

**Reproduction**
Rightclick where the phone is screwed down and see two pop up. Normandy does not have the issue.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/99b9e213-ac51-4f9e-9c95-849165294107)

**Additional context**
N/A

**Comment by DrSmugleaf** [comment]
Fixed in https://github.com/RMC-14/RMC-14/pull/4685
