### ISSUE TITLE
Hijack announcement does not transmit shipside in text

### ISSUE THREAD

**Issue by ArdentSpark** [RMC-14/RMC-14#4686]
## Description
Hijack announcement no longer transmits via radio, I presume it sends to marine common still while we use almayer frequency

**Reproduction**
get owned
queen hijacks
be a marine shipside, no entry in the chatlog

**Screenshots**

**Additional context**

**Comment by DrSmugleaf** [comment]
Yeah comms broke this since the dropship speaks from the planet
Its supposed to be an ARES-style announcement so that would fix it
