### ISSUE TITLE
watermelon helmets can be made and have upstream armor

### ISSUE THREAD

**Issue by Kadeo64** [RMC-14/RMC-14#4695]
## Description
butchering a watermelon lets you create a watermelon helmet. This helmet has upstream armor.
**Reproduction**
enter botany
plant watermelon
wait 3 years for it to grow
take a knife
RIGHT CLICK > BUTCHER (do not click on the melon that turns it into slices)
shift + click helmet 
click armor value examine
see 5% upstream blunt resist
**Additional context**
most likely a non-issue

**Comment by Skarletto** [comment]
fixed by #4767
