### ISSUE TITLE
First aid kits cannot fit inside satchels/similar containers.

### ISSUE THREAD

**Issue by troytroy400** [RMC-14/RMC-14#4700]
## Description
You cannot store first aid kits in any applicable container. For parity they should be stowable. 

**Reproduction**
Attempt to put a first aid kit in a satchel.

**Screenshots**
N/A

**Additional context**
Parity.

**Comment by troytroy400** [comment]
And for proof of parity:
![image](https://github.com/user-attachments/assets/70db38a0-b948-4b82-ad17-4729def6bf14)

**Comment by Vermidia** [comment]
You can't without medical skill

**Comment by troytroy400** [comment]
> You can't without medical skill (which we haven't implemented how it works specifically yet) for stuff like this

Oh, that makes a lot more sense then.

**Comment by Vermidia** [comment]
Storing Medical Kits and Engineering kits with skill in backpacks/satchels is in now
