### ISSUE TITLE
remove the instrument component from the microphone

### ISSUE THREAD

**Issue by Skarletto** [RMC-14/RMC-14#4727]
i get wanting to have a fun prop for the correspondent, but people singing goofy songs before going to war (OR EVEN DURING) isnt exactly the right vibe for the game imo

it's actually really weird to think about, how some person could be playing spongebob music while we're literally getting acided to death, but maybe that's just me 😄

**Comment by Kadeo64** [comment]
as #1 correspondent in playtime i approve this issue

correspondent should not be a role to show off midi collections

**Comment by DummeHytteOst** [comment]
resolved by #4949
