### ISSUE TITLE
Damage multipliers get applied twice for revolvers

### ISSUE THREAD

**Issue by crystalHex** [RMC-14/RMC-14#4786]
## Description

Adding a `GunDamageModifier` component to a revolver causes the damage multiplier to apply twice, e.g. a modifier of 1.5 would actually increase the damage dealt by 2.25 times.

**Reproduction**

1. Add the `GunDamageModifier` component to any revolver (e.g. Mateba), either through the .yml or debug environment.
2. Set the multiplier of the component to any value.
3. Fire the revolver and see that it's damage has been multiplied by the modifier twice.

**Screenshots**

**Additional context**

This is currently only relevant for the Mateba, as that should have a damage multiplier of 1.5, but it might become relevant for any future revolvers to be added.
Some time ago, this issue was also present for rifles (e.g. the M4SPR had a multiplier of 1.96 instead of 1.4), but that was fixed somehow. I'm not sure how and I've already spent a few hours trying to dig through the code without finding the cause of the issue, so I'm just putting this up so someone smarter than me can take a look at it.

**Comment by DrSmugleaf** [comment]
Fixed in https://github.com/RMC-14/RMC-14/commit/e331f3e327e8bd588c1c6b7bacdee666d57dd750
