### ISSUE TITLE
the M276 pattern XM51 holster rig needs to fit on exoslot when wearing armor

### ISSUE THREAD

**Issue by Skarletto** [RMC-14/RMC-14#4851]
pew pew pew
![image](https://github.com/user-attachments/assets/0e373835-8d32-4098-aa08-cc035bcdd5ad)

you cant wear the holster rig on exoslot if you have no armor
![image](https://github.com/user-attachments/assets/d318258d-3b86-4dc7-a700-38e1a0554841)

![image](https://github.com/user-attachments/assets/e74b10be-34c1-4e06-bc0c-5c6f725c440e)

**Comment by Vermidia** [comment]
Needs to be put on the base armor suitstorage whitelist and it's cloth comp needs to have suitstorage added there.

**Comment by crystalHex** [comment]
#4782
