### ISSUE TITLE
sus toolbox on kutjevo

### ISSUE THREAD

**Issue by Kadeo64** [RMC-14/RMC-14#4941]
## Description
there is a suspicious syndicate toolbox on kutjevo. It can hold tools and fit in a backpack, which is nested storage.
**Additional context**
I don't know where it is, and it seemingly has a whitelist so it can only fit tools, but it exists and it's still nested storage, it lets you fit a full tool set in a single large-size item.

**Comment by Dutch-VanDerLinde** [comment]
this is intended, it's an item from 13

**Comment by Kadeo64** [comment]
> this is intended, it's an item from 13

nested storage is intentional too?

**Comment by PolarTundraa** [comment]
> > this is intended, it's an item from 13
> 
> nested storage is intentional too?

It says so in its item description

**Comment by Skarletto** [comment]
Intended, parity, it has nested inventory on cm13 as well
one of the wonders of OP gear on kutjevo
