### ISSUE TITLE
Mini sentries shouldn't dodge spit.

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#4986]
## Description

Parity, rn for some reason unlike other sentries you can't just spit at them.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Dutch-VanDerLinde** [comment]
they are missing fixtures i think is BulletImpassable so the no collision makes it so they literally can't collide with anything

**Comment by DummeHytteOst** [comment]
fixed by #5169
