### ISSUE TITLE
Burrower is invisible in the hivemind vision

### ISSUE THREAD

**Issue by Jarmer123** [RMC-14/RMC-14#5000]
## Description
You can not see Burrowers through wall with hivemind vision (they are visible if they are burrowed), you can still see HP and plasma however

**Comment by blueDev2** [comment]
Did you use control mob when you found this issue at all?

**Comment by blueDev2** [comment]
I can't replicate this

**Comment by blueDev2** [comment]
Nevermind, I misunderstood the issue, I have replicated this issue.
