### ISSUE TITLE
burrower stomp should stun 3 tiles out

### ISSUE THREAD

**Issue by Skarletto** [RMC-14/RMC-14#5012]
rn its like 7 and that is definitely not intended and VERY STRONG

**Comment by DrSmugleaf** [comment]
Fixed in https://github.com/RMC-14/RMC-14/pull/5006
It was already uploaded live to the server yesterday
We made it 4 instead since that makes the total area the same in a circle radius

**Comment by Skarletto** [comment]
aaaaaaaaaaaaaaa
