### ISSUE TITLE
sensor tower sprite is layered over humanoids

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#5034]
## Description

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Skarletto** [comment]
is the issue refering to something else or does it refer to this, because it's parity
![image](https://github.com/user-attachments/assets/bcc83907-1646-472c-950c-488a970b1d1c)

**Comment by Skarletto** [comment]
okay idk why but the wording confused me. 

The sensor tower should be layered over humanoids

**Comment by Skarletto** [comment]
![image](https://github.com/user-attachments/assets/62c07a6b-e4f9-4162-be95-15b6c1f785c2)
this is parity
assuming this is so marines dont just shuffle underneath to stop xenos from hitting them but idk

the small one is layered over but this isn't the right tower, the one we have in rmc is parity (experimental sensor tower)
![image](https://github.com/user-attachments/assets/dc17e710-9884-411b-b29c-329cf1d0ab22)
