### ISSUE TITLE
M45 Pattern Ghillie Armor

### ISSUE THREAD

**Issue by QuietlyWhisper** [RMC-14/RMC-14#511]
https://cm-ss13.com/wiki/Marine_Equipment#M45_Pattern_Ghillie_Armor

- [x] sprite
- [x] yml
- [ ] abilities

**Comment by QuietlyWhisper** [comment]
![image](https://github.com/CM-14/CM-14/assets/121047731/a72b24d8-2c59-4cab-b2d9-f10614e87317)

**Comment by Dutch-VanDerLinde** [comment]
Fixed
