### ISSUE TITLE
headbands don't have proper storage

### ISSUE THREAD

**Issue by Carolyn3114** [RMC-14/RMC-14#5133]
## Description

tried putting autoinjector into a headband and it didn't work, it's supposed to carry items and it has 2 slots you can't use.

![Screenshot 2024-12-13 204711](https://github.com/user-attachments/assets/c20000e9-907c-48b5-a024-63a96f567ab6)

**Comment by Dutch-VanDerLinde** [comment]
this is parity right

**Comment by Carolyn3114** [comment]
> this is parity right

according to smugleaf no

**Comment by Vermidia** [comment]
Issue is headbands shouldn't have storage at all with parity, so that's what needs to be fixed

**Comment by Dutch-VanDerLinde** [comment]
ok so it just inherits from caps and stuff, which have storage for cigarettes only

**Comment by Carolyn3114** [comment]
> ok so it just inherits from caps and stuff, which have storage for cigarettes only

I was told it could hold injectors in cm13, this is cooked
