### ISSUE TITLE
Xenos Finding Invisible Spec From Spamming Right Click

### ISSUE THREAD

**Issue by Kezu02** [RMC-14/RMC-14#5234]
## Description

Title. Saw someone in LOOC say they couldn't see the sniper that went invi and only found them through the context menu. Doesn't seem fair that you can use the UI to beat spec cloaking.

**Comment by deltanedas** [comment]
this is actually parity im told

**Comment by Vermidia** [comment]
yep, it also effects lurkers, parasites, and everything like that.

**Comment by Skarletto** [comment]
this is intended and is parity
they're not meant to be completely invisible and if scout runs into the hive invis then he should get punished for overextending, would be kinda ass if he was just not able to be seen at all
as for sniper when we have aimed shot you'll see his aim spot anyways (it shows a giga red line in his line of fire) + when he shoots he flashes

also everything verm said
![Uploading image.png…]()
