### ISSUE TITLE
radio channel long range needs to be split between long range and requires server

### ISSUE THREAD

**Issue by QuietlyWhisper** [RMC-14/RMC-14#610]
![image](https://github.com/CM-14/CM-14/assets/121047731/e43e9fb0-8fae-4352-8bf3-7f90212b6c80)
this should be two separate variables, so telecomms can be built on planet and work between maps

**Comment by Tunguso4ka** [comment]
and also antennas?

**Comment by QuietlyWhisper** [comment]
finished with proper telecoms
